from . import test_access_rights
from . import test_advanced_edge_cases
from . import test_appeals_and_views
from . import test_audit_edge_cases
from . import test_cache_coherence
from . import test_config_settings
from . import test_controllers
from . import test_documentation
from . import test_exhaustive_isolation
from . import test_gdpr_base
from . import test_group_moderation
from . import test_lifecycle_and_groups
from . import test_moderation
from . import test_orm_security
from . import test_page_limits
from . import test_performance_regressions
from . import test_privacy_gdpr
from . import test_qweb_context
from . import test_robustness_and_boundaries
from . import test_sdk_extensibility
from . import test_security_edge_cases
from . import test_simulation
from . import test_subscriptions
from . import test_ui_personas
from . import test_ui_tours
from . import test_user_websites_blog_post
from . import test_utils
from . import test_xpath_rendering
