// SPDX-License-Identifier: LGPL-3.0-or-later
//! Fixed-point `log2`/`exp2` via 257-entry lookup tables (generated by
//! `examples/ambe_fixed_generate_explog_tables.rs` into [`super::explog_table`]) plus linear
//! interpolation -- the fixed-point equivalent of the float dequantize chain's own `.log2()`,
//! `.exp()`-of-`0.693*x` (i.e. `2^x`, since `0.693 ~= ln(2)`), and `.powf()` calls (`enhancement.rs`'s
//! `powf(0.25)`/`powf(0.375)` and `reconstruct.rs`'s `2f64.powf(log2_m)` are all expressible as
//! `exp2(k * log2(x))` for a constant `k`).
//!
//! Both functions operate on Q16.16 values (see [`super::super`]'s own doc comment for the numeric
//! convention): [`log2_q16`] takes a positive Q16.16 magnitude and returns its base-2 logarithm, also
//! in Q16.16 (so it can represent negative results, e.g. `log2(0.5) = -1.0` for an input less than
//! one full unit). [`exp2_q16`] is the inverse: a Q16.16 exponent (may be negative) in, a positive
//! Q16.16 magnitude out.

use super::explog_table::{EXP2_FRAC_LEN, EXP2_FRAC_Q16_16, LOG2_FRAC_LEN, LOG2_FRAC_Q16_16};

/// `log2(x)` in Q16.16, for a positive Q16.16 `x`. Never panics: a non-positive `x` (log2 is
/// undefined for zero, complex for negative) returns `i32::MIN` as a saturating "negative infinity"
/// sentinel, matching this crate's own established "never panic across the full input range"
/// convention rather than mirroring `f64::log2`'s own `-inf`/`NaN` (which have no exact fixed-point
/// representation).
pub fn log2_q16(x: i32) -> i32 {
    if x <= 0 {
        return i32::MIN;
    }
    let xu = x as u32;
    let msb = 31 - xu.leading_zeros(); // position of the leading 1 bit, 0..=31

    // Normalize `xu` so its leading 1 sits at bit 30, maximizing the precision of the 30-bit
    // fraction the table lookup below reads from.
    let shift = 30i32 - msb as i32;
    let normalized = if shift >= 0 { xu << shift } else { xu >> (-shift) };
    let frac_bits = normalized & ((1u32 << 30) - 1); // the 30-bit fraction below the implicit leading 1
    let index = (frac_bits >> 22) as usize; // top 8 bits of that fraction -> table index, 0..255
    let sub_frac = (frac_bits & ((1 << 22) - 1)) as i64; // remaining 22 bits, for interpolation

    let a = LOG2_FRAC_Q16_16[index.min(LOG2_FRAC_LEN - 2)] as i64;
    let b = LOG2_FRAC_Q16_16[(index + 1).min(LOG2_FRAC_LEN - 1)] as i64;
    let interp = a + (((b - a) * sub_frac) >> 22);

    // log2(xu) [xu treated as a plain integer] = msb + interp/65536. `x` is itself Q16.16
    // (x_real = xu / 2^16), so log2(x_real) = log2(xu) - 16.
    let log2_raw_q16 = (msb as i64) * 65536 + interp;
    (log2_raw_q16 - (16i64 << 16)) as i32
}

/// `2^y` in Q16.16, for a Q16.16 exponent `y` (which may be negative). Saturates to `0` or
/// `i32::MAX` rather than wrapping/panicking if `y` is far enough outside a representable range
/// that the true result over- or under-flows `i32`'s own Q16.16 range -- never a silent wraparound.
///
/// **A real, inherent precision limit, not a bug**: Q16.16 has a *fixed* 16 fractional bits
/// regardless of magnitude, so a result near `2^-10` (about `0.001`) has only ~6 significant bits of
/// relative precision left (`2^16 * 2^-10 = 2^6`), and a result near `2^-16` has essentially none.
/// This is the same property that makes fixed point unsuitable for a wide dynamic range in the first
/// place -- `log2_q16`'s own error stays small in *absolute* Q16.16 terms across its whole domain,
/// but `exp2_q16`'s *relative* error necessarily grows for a very negative `y`, because the final
/// right-shift by `-y`'s integer part discards exactly that many low bits of an inherently
/// fixed-width result. Round-to-nearest on that shift (below) recovers close to half a bit versus
/// naive truncation, but does not remove the underlying limit. Callers in this crate's own
/// dequantize/synthesis chain are expected to keep amplitudes scaled such that `y` rarely goes below
/// roughly `-8` in practice (a real check against the actual dequantize output, once ported, belongs
/// in that port's own tests -- this module only guarantees the *table-and-interpolation* math is
/// correct, not that every caller's chosen scaling stays inside the format's comfortable range).
pub fn exp2_q16(y: i32) -> i32 {
    let n = y >> 16; // arithmetic shift: floor(y / 65536), correct for negative y in two's complement.
    let frac = (y & 0xFFFF) as u32; // 0..=65535, the fractional part `f` (0..1) scaled by 65536.

    let index = (frac >> 8) as usize; // top 8 bits of `frac` -> table index, 0..255
    let sub_frac = (frac & 0xFF) as i64; // remaining 8 bits, for interpolation
    let a = EXP2_FRAC_Q16_16[index.min(EXP2_FRAC_LEN - 2)] as i64;
    let b = EXP2_FRAC_Q16_16[(index + 1).min(EXP2_FRAC_LEN - 1)] as i64;
    let interp = a + (((b - a) * sub_frac) >> 8); // Q16.16, in [65536, 131072): 2^f.

    if n >= 0 {
        if n >= 15 || interp > (i32::MAX as i64 >> n) {
            i32::MAX
        } else {
            (interp << n) as i32
        }
    } else if -n >= 63 {
        0
    } else {
        // Round to nearest rather than truncate: adding half the divisor before shifting is the
        // standard fixed-point rounding idiom, and recovers close to half a bit of precision that
        // plain truncation would otherwise throw away for free.
        let shift = -n;
        ((interp + (1i64 << (shift - 1))) >> shift) as i32
    }
}
