// SPDX-License-Identifier: LGPL-3.0-or-later
//! Fixed-point sine/cosine via a quarter-wave lookup table (generated by
//! `examples/ambe_fixed_generate_trig_table.rs` into [`super::trig_table`]) plus linear
//! interpolation between entries -- the fixed-point equivalent of every `.sin()`/`.cos()` call in
//! the floating-point synthesis chain (e.g. `voiced_synthesis::synthesize`'s own per-harmonic
//! oscillators).
//!
//! **Phase convention**: a phase is a wrapping `u32` where a full turn (`2*pi` radians) is
//! `1u32 << 32` -- overflow-wraps for free, which *is* the modulo-`2*pi` reduction a floating-point
//! implementation has to do explicitly (see [`super::super`]'s own doc comment). A quarter turn is
//! therefore `1u32 << 30`. The result of [`sin_q16`]/[`cos_q16`] is Q16.16 (`i32`, low 16 bits
//! fractional), ranging `-65536..=65536` for `-1.0..=1.0`.

use super::trig_table::{QUARTER_SINE_LEN, QUARTER_SINE_Q16_16};

const QUARTER_TURN: u32 = 1 << 30;
/// `QUARTER_TURN / (QUARTER_SINE_LEN - 1)` as a right-shift amount -- the table has `2^8 + 1`
/// entries spanning a `2^30`-wide quarter turn, so each table interval is exactly `2^22` wide, a
/// power of two chosen precisely so indexing and fractional-part extraction are both plain shifts.
const INDEX_SHIFT: u32 = 22;
const FRAC_MASK: u32 = (1 << INDEX_SHIFT) - 1;

/// Linearly interpolates the quarter-wave table at `x` (`0..=QUARTER_TURN`), returning a Q16.16
/// sine value for the angle `x` represents within `[0, pi/2]`.
fn quarter_sine_interp(x: u32) -> i32 {
    let index = (x >> INDEX_SHIFT) as usize;
    if index + 1 >= QUARTER_SINE_LEN {
        return QUARTER_SINE_Q16_16[QUARTER_SINE_LEN - 1];
    }
    let frac = (x & FRAC_MASK) as i64;
    let a = QUARTER_SINE_Q16_16[index] as i64;
    let b = QUARTER_SINE_Q16_16[index + 1] as i64;
    (a + (((b - a) * frac) >> INDEX_SHIFT)) as i32
}

/// `sin(phase)` in Q16.16, `phase` interpreted per this module's own turn convention (`1u32 << 32`
/// = `2*pi`). Exact quadrant folding from the single quarter-wave table, not a second table.
pub fn sin_q16(phase: u32) -> i32 {
    let quadrant = phase >> 30;
    let r = phase & (QUARTER_TURN - 1);
    match quadrant {
        0 => quarter_sine_interp(r),
        1 => quarter_sine_interp(QUARTER_TURN - r),
        2 => -quarter_sine_interp(r),
        _ => -quarter_sine_interp(QUARTER_TURN - r),
    }
}

/// `cos(phase)` in Q16.16 -- `sin` shifted a quarter turn, per the identity `cos(x) = sin(x + pi/2)`.
pub fn cos_q16(phase: u32) -> i32 {
    sin_q16(phase.wrapping_add(QUARTER_TURN))
}

// No `#[cfg(test)]` module here: any test comparing this module's output against `f64::sin`/`cos`
// needs floating point to compute the expected value, which would put `f64` tokens inside
// `src/ambe/fixed` and defeat the whole-tree "zero floating point" check this crate enforces (see
// `super::super`'s own doc comment) -- `cargo clippy`'s `#![deny(clippy::float_arithmetic)]` lints
// `#[cfg(test)]` code too, so such a test would also fail the build, not just the intent. Those
// tests live in `tests/ambe_fixed_general.rs` instead, as ordinary integration tests calling this
// module's public API from outside the crate. Fixed-point-only self-checks (the Pythagorean
// identity, exact cardinal angles, magnitude bounds) could in principle live here since they touch
// no float at all, but are kept alongside the f64-comparison tests in the same integration test
// file instead, so every claim this module's doc comment makes about its own accuracy is verified
// in one place.
