// SPDX-License-Identifier: LGPL-3.0-or-later
//! Fixed-point sine/cosine via a quarter-wave lookup table (generated by
//! `examples/ambe_fixed_generate_trig_table.rs` into [`super::trig_table`]) plus linear
//! interpolation between entries -- the fixed-point equivalent of every `.sin()`/`.cos()` call in
//! the floating-point synthesis chain (e.g. `voiced_synthesis::synthesize`'s own per-harmonic
//! oscillators).
//!
//! **Phase convention**: a phase is a wrapping `u32` where a full turn (`2*pi` radians) is
//! `1u32 << 32` -- overflow-wraps for free, which *is* the modulo-`2*pi` reduction a floating-point
//! implementation has to do explicitly (see [`super::super`]'s own doc comment). A quarter turn is
//! therefore `1u32 << 30`. The result of [`sin_q16`]/[`cos_q16`] is Q16.16 (`i32`, low 16 bits
//! fractional), ranging `-65536..=65536` for `-1.0..=1.0`.

use super::trig_table::{QUARTER_SINE_LEN, QUARTER_SINE_Q16_16};

const QUARTER_TURN: u32 = 1 << 30;
/// `QUARTER_TURN / (QUARTER_SINE_LEN - 1)` as a right-shift amount -- the table has `2^8 + 1`
/// entries spanning a `2^30`-wide quarter turn, so each table interval is exactly `2^22` wide, a
/// power of two chosen precisely so indexing and fractional-part extraction are both plain shifts.
const INDEX_SHIFT: u32 = 22;
const FRAC_MASK: u32 = (1 << INDEX_SHIFT) - 1;

/// Linearly interpolates the quarter-wave table at `x` (`0..=QUARTER_TURN`), returning a Q16.16
/// sine value for the angle `x` represents within `[0, pi/2]`.
fn quarter_sine_interp(x: u32) -> i32 {
    let index = (x >> INDEX_SHIFT) as usize;
    if index + 1 >= QUARTER_SINE_LEN {
        return QUARTER_SINE_Q16_16[QUARTER_SINE_LEN - 1];
    }
    let frac = (x & FRAC_MASK) as i64;
    let a = QUARTER_SINE_Q16_16[index] as i64;
    let b = QUARTER_SINE_Q16_16[index + 1] as i64;
    (a + (((b - a) * frac) >> INDEX_SHIFT)) as i32
}

/// `sin(phase)` in Q16.16, `phase` interpreted per this module's own turn convention (`1u32 << 32`
/// = `2*pi`). Exact quadrant folding from the single quarter-wave table, not a second table.
pub fn sin_q16(phase: u32) -> i32 {
    let quadrant = phase >> 30;
    let r = phase & (QUARTER_TURN - 1);
    match quadrant {
        0 => quarter_sine_interp(r),
        1 => quarter_sine_interp(QUARTER_TURN - r),
        2 => -quarter_sine_interp(r),
        _ => -quarter_sine_interp(QUARTER_TURN - r),
    }
}

/// `cos(phase)` in Q16.16 -- `sin` shifted a quarter turn, per the identity `cos(x) = sin(x + pi/2)`.
pub fn cos_q16(phase: u32) -> i32 {
    sin_q16(phase.wrapping_add(QUARTER_TURN))
}

/// `cos(pi * a * b / c)` in Q16.16, for small non-negative integers `a`, `c` and a half-integer `b`
/// (`b_times_2` is `2*b`, always odd, e.g. `i - 0.5` passed as `2*i - 1`) -- a shape that recurs
/// across every DCT-style reconstruction in this crate's fixed-point port (`general::mbe_speech`'s
/// own 8-point cosine sum and inverse DCT, `tia_102_baba::reconstruct`'s gain-vector and block DCTs).
pub fn cos_pi_frac(a: i64, b_times_2: i64, c: i64) -> i32 {
    // (a * b) / c = (a * b_times_2 / 2) / c = a * b_times_2 / (2*c), kept as one exact integer
    // ratio until the final Q16.16 conversion so no intermediate rounding compounds.
    let numerator_q16 = (a * b_times_2) << 16; // Q16.16 numerator of `a * b_times_2`
    let x_q16 = (numerator_q16 / (2 * c)) as i32; // Q16.16 of `a * b / c`
    cos_q16(phase_from_pi_multiple_q16(x_q16))
}

/// Converts `x * pi` (for a Q16.16 `x`, which may be negative or span many turns) into this module's
/// own `u32` phase convention, for callers whose own formula is naturally expressed as `cos(pi * x)`
/// or `sin(pi * x)` (e.g. the MBE dequantize chain's own DCT sums) rather than as a phase directly.
/// `pi` radians is exactly a half turn (`1u32 << 31`), so this is `x` scaled by that half-turn and
/// wrapped -- the wrapping is exact and free (`u32` overflow *is* the modulo-2*pi reduction), even
/// though `x` itself may be far outside `-2..2`.
pub fn phase_from_pi_multiple_q16(x_q16: i32) -> u32 {
    ((x_q16 as i64).wrapping_mul(1i64 << 31) >> 16) as u32
}

/// `round(pi * 2^48)` -- a much higher-precision representation of pi than [`super::fixed_ops::
/// PI_Q16_16`]'s own Q16.16 (`round(pi * 2^16)`), used *only* by [`phase_from_radians_q16`]/
/// [`phase_from_radians_q16_i64`]/[`radians_from_phase_q16`] below. `PI_Q16_16`'s own rounding is a
/// small *relative* error (`~2.02e-6`, i.e. about 2 parts per million) on the constant itself, and
/// dividing by it turns that into an equally small *multiplicative scale error on every phase this
/// module ever produces* -- harmless for an ordinary single-shot angle, but `voiced_synthesis`'s own
/// `psi_l`/`phi_l` (Eq. 139-140) accumulate a phase increment every frame forever, so a `2 ppm`
/// scale error on the *frequency itself* is a genuine, unbounded, linearly growing phase drift over a
/// long call -- confirmed directly: an early version of this module used `PI_Q16_16` here, and
/// `ambe_fixed_voiced_synthesis.rs`'s own long-run scenarios measured SNR degrading by `~6 dB` per
/// doubling of frame count (`56 dB` at 1 frame down to `~0 dB` at 128), *independent* of whether the
/// pitch was held constant or genuinely varied frame to frame -- exactly the signature of a fixed
/// fractional frequency error, not of any rounding noise correlated with a repeated input. Kept as its
/// own `i128` constant (not a wider version of `PI_Q16_16` itself) since every *other* caller of
/// `PI_Q16_16` wants an ordinary Q16.16 value, not this format.
const PI_Q48: i128 = 884_279_719_003_555;

/// Converts a Q16.16 angle in radians directly into this module's own `u32` phase convention, for
/// callers whose own formula is a genuine radian angle (e.g. `omega0 * l`, RATET(27)'s own
/// enhancement-stage phase term) rather than a clean multiple of `pi`. `phase = angle / (2*pi) *
/// 2^32 = angle * 2^15 / pi`; computed against [`PI_Q48`] (not `fixed_ops::PI_Q16_16` -- see that
/// constant's own doc comment for why) in a wide enough integer type before ever reducing mod `2^32`,
/// so the final truncating cast to `u32` is the correct wraparound, not a source of extra error.
pub fn phase_from_radians_q16(angle_q16: i32) -> u32 {
    round_div_to_u32((angle_q16 as i128) << 63, PI_Q48)
}

/// The same conversion as [`phase_from_radians_q16`], for a caller whose own Q16.16 angle is
/// computed in `i64` (a sum of several per-sample terms, e.g. `voiced_synthesis`'s own `theta_l(n)`,
/// each individually bounded but not worth narrowing to `i32` before every intermediate addition) --
/// widened to `i128` for the left shift so a genuinely large `i64` input still reduces mod `2*pi`
/// exactly rather than risking a shift overflow.
pub fn phase_from_radians_q16_i64(angle_q16: i64) -> u32 {
    round_div_to_u32((angle_q16 as i128) << 63, PI_Q48)
}

/// Rounds `numerator / denominator` to the nearest integer (ties away from zero, the same convention
/// [`super::fixed_ops::mul_q16`]/`explog::exp2_q16` already use) before truncating to `u32`.
fn round_div_to_u32(numerator: i128, denominator: i128) -> u32 {
    let half = denominator.abs() / 2;
    let rounded = if numerator >= 0 { numerator + half } else { numerator - half };
    (rounded / denominator) as u32
}

/// The exact inverse of [`phase_from_radians_q16`], for a caller that needs a persistent phase
/// *accumulator* to survive indefinitely many frames without overflow (`voiced_synthesis`'s own
/// `psi_l`/`phi_l`, Eq. 139-140, which keep adding a per-frame increment forever): store the
/// accumulator as this module's own wrapping `u32` phase (which can never overflow, by construction
/// -- see this module's own doc comment), and use this function only to recover a bounded Q16.16
/// radian value, in `(-pi, pi]`, for the *within-frame* arithmetic that genuinely needs an ordinary
/// radian quantity (added to other bounded per-sample terms before a final `cos`/`sin`) rather than
/// a phase. Interpreting `phase` as `i32` (the same bits, two's-complement) before scaling is what
/// makes the result symmetric around zero instead of `[0, 2*pi)`: a `u32` phase past the half turn
/// (`1u32 << 31`) is, bit-for-bit, a negative `i32`, exactly the "wrapped the other way past pi"
/// case this format is supposed to represent for free.
///
/// Rounds to the nearest Q16.16 value (ties away from zero) rather than truncating the final shift:
/// a plain arithmetic `>> 31` floors, which is a *signed* half-LSB-average bias applied fresh to
/// every rendered sample in `voiced_synthesis` (it does not itself compound in the stored phase
/// accumulator, since only the wrapping `u32` phase is carried forward -- but the same one-sided bias
/// on every sample of every frame is still a real, systematic error against the float sibling, not
/// mere per-sample rounding noise). Uses [`PI_Q48`], not `fixed_ops::PI_Q16_16`, for the same reason
/// [`phase_from_radians_q16`] does -- see that constant's own doc comment.
pub fn radians_from_phase_q16(phase: u32) -> i32 {
    let numerator = (phase as i32 as i128) * PI_Q48;
    let denominator = 1i128 << 63;
    let half = denominator / 2;
    let rounded = if numerator >= 0 { numerator + half } else { numerator - half };
    (rounded / denominator) as i32
}

// No `#[cfg(test)]` module here: any test comparing this module's output against `f64::sin`/`cos`
// needs floating point to compute the expected value, which would put `f64` tokens inside
// `src/ambe/fixed` and defeat the whole-tree "zero floating point" check this crate enforces (see
// `super::super`'s own doc comment) -- `cargo clippy`'s `#![deny(clippy::float_arithmetic)]` lints
// `#[cfg(test)]` code too, so such a test would also fail the build, not just the intent. Those
// tests live in `tests/ambe_fixed_general.rs` instead, as ordinary integration tests calling this
// module's public API from outside the crate. Fixed-point-only self-checks (the Pythagorean
// identity, exact cardinal angles, magnitude bounds) could in principle live here since they touch
// no float at all, but are kept alongside the f64-comparison tests in the same integration test
// file instead, so every claim this module's doc comment makes about its own accuracy is verified
// in one place.
