#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright © Bruce Perens K6BP. All Rights Reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later

import json
import os
import sys
import tempfile
import unittest
from unittest.mock import MagicMock, patch

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import pgbackrest_sidecar as sidecar  # noqa: E402


# [@ANCHOR: backup_management:COMM_test_pgbackrest_sidecar_validate_cmd]
class TestValidateRequestCmd(unittest.TestCase):
    # Tests [@ANCHOR: backup_management:COMM_pgbackrest_sidecar_validate_request]

    def test_accepts_a_real_local_backup_cmd(self):
        sidecar._validate_request_cmd(["pgbackrest", "backup", "--stanza=hams_prod", "--type=full"])

    def test_accepts_a_real_s3_backup_cmd(self):
        sidecar._validate_request_cmd(
            [
                "pgbackrest",
                "backup",
                "--stanza=hams_prod",
                "--type=full",
                "--repo1-type=s3",
                "--repo1-s3-bucket=hams-backups",
                "--repo1-s3-endpoint=s3.us-west-002.backblazeb2.com",
                "--repo1-s3-region=us-east-1",
                "--repo1-path=/hams_prod",
                "--repo1-retention-full=5",
            ]
        )

    def test_rejects_non_pgbackrest_binary(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd(["rm", "-rf", "/"])

    def test_rejects_non_backup_operation(self):
        # restore/info/stanza-create etc. are all out of scope for this
        # sidecar -- only "backup" is ever generated by main.py's own
        # _pgbackrest_requires_sidecar() gate, and this must re-enforce that
        # on its own side rather than trust it.
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd(["pgbackrest", "restore", "--stanza=hams_prod"])

    def test_rejects_shell_metacharacters_in_stanza(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd(["pgbackrest", "backup", "--stanza=hams_prod; rm -rf /"])

    def test_rejects_missing_stanza(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd(["pgbackrest", "backup", "--type=full"])

    def test_rejects_invalid_backup_type(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd(
                ["pgbackrest", "backup", "--stanza=hams_prod", "--type=$(whoami)"]
            )

    def test_rejects_an_unrecognized_flag(self):
        # The allowlist is exhaustive by design -- a flag main.py's own cmd
        # construction has never produced (e.g. an injected --repo1-cipher-pass)
        # must be refused outright, not silently passed through to postgres.
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd(
                ["pgbackrest", "backup", "--stanza=hams_prod", "--repo1-cipher-pass=anything"]
            )

    def test_rejects_non_list_cmd(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd("pgbackrest backup --stanza=hams_prod")

    def test_rejects_empty_cmd(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_cmd([])


# [@ANCHOR: backup_management:COMM_test_pgbackrest_sidecar_validate_env]
class TestValidateRequestEnv(unittest.TestCase):
    # Tests [@ANCHOR: backup_management:COMM_pgbackrest_sidecar_validate_env]

    def test_accepts_empty_env(self):
        sidecar._validate_request_env({})

    def test_accepts_the_two_allowed_secret_keys(self):
        sidecar._validate_request_env(
            {"PGBACKREST_REPO1_S3_KEY": "a", "PGBACKREST_REPO1_S3_KEY_SECRET": "b"}
        )

    def test_rejects_an_unexpected_key(self):
        # Defends against a request (however it was produced) trying to
        # smuggle PATH/LD_PRELOAD/etc. into the privileged subprocess's env.
        with self.assertRaises(ValueError):
            sidecar._validate_request_env({"LD_PRELOAD": "/opt/evil/evil.so"})

    def test_rejects_non_string_values(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_env({"PGBACKREST_REPO1_S3_KEY": 12345})

    def test_rejects_non_dict(self):
        with self.assertRaises(ValueError):
            sidecar._validate_request_env(["PGBACKREST_REPO1_S3_KEY=a"])


# [@ANCHOR: backup_management:COMM_test_pgbackrest_sidecar_process_one]
class TestProcessOne(unittest.TestCase):
    # Tests [@ANCHOR: backup_management:COMM_pgbackrest_sidecar_process_one]

    def setUp(self):
        self._tmpdir = tempfile.mkdtemp(prefix="pgbackrest_sidecar_process_one_")
        self._patcher = patch.object(sidecar, "SPOOL_DIR", self._tmpdir)
        self._patcher.start()
        self.addCleanup(self._patcher.stop)

    def _write_request(self, job_id, cmd, env=None):
        request_path = os.path.join(self._tmpdir, f"request-{job_id}.json")
        with open(request_path, "w") as f:
            json.dump({"cmd": cmd, "env": env or {}}, f)
        return request_path

    @patch("pgbackrest_sidecar.subprocess.run")
    def test_runs_the_validated_cmd_as_the_configured_user(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="backup ok")
        request_path = self._write_request(
            "1", ["pgbackrest", "backup", "--stanza=hams_prod", "--type=full"]
        )

        sidecar._process_one(request_path)

        run_cmd = mock_run.call_args.args[0]
        self.assertEqual(
            run_cmd,
            ["runuser", "-u", sidecar.RUN_AS_USER, "--", sidecar.PGBACKREST_BIN, "backup", "--stanza=hams_prod", "--type=full"],
        )
        result_path = os.path.join(self._tmpdir, "result-1.json")
        with open(result_path) as f:
            result = json.load(f)
        self.assertEqual(result, {"return_code": 0, "output": "backup ok"})
        self.assertFalse(os.path.exists(request_path))

    @patch("pgbackrest_sidecar.subprocess.run")
    def test_passes_s3_secrets_as_env_not_argv(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="")
        request_path = self._write_request(
            "2",
            ["pgbackrest", "backup", "--stanza=hams_prod", "--repo1-type=s3"],
            env={"PGBACKREST_REPO1_S3_KEY": "AKIAFAKE", "PGBACKREST_REPO1_S3_KEY_SECRET": "sekrit"},
        )

        sidecar._process_one(request_path)

        run_env = mock_run.call_args.kwargs["env"]
        self.assertEqual(run_env["PGBACKREST_REPO1_S3_KEY"], "AKIAFAKE")
        self.assertEqual(run_env["PGBACKREST_REPO1_S3_KEY_SECRET"], "sekrit")
        run_cmd = mock_run.call_args.args[0]
        joined = " ".join(run_cmd)
        self.assertNotIn("AKIAFAKE", joined)
        self.assertNotIn("sekrit", joined)

    @patch("pgbackrest_sidecar.subprocess.run")
    def test_a_failing_backup_still_writes_a_readable_result(self, mock_run):
        mock_run.return_value = MagicMock(returncode=1, stdout="ERROR: [056] unable to find primary cluster")
        request_path = self._write_request(
            "3", ["pgbackrest", "backup", "--stanza=hams_prod"]
        )

        sidecar._process_one(request_path)

        with open(os.path.join(self._tmpdir, "result-3.json")) as f:
            result = json.load(f)
        self.assertEqual(result["return_code"], 1)
        self.assertIn("unable to find primary cluster", result["output"])

    @patch("pgbackrest_sidecar.subprocess.run")
    def test_an_invalid_request_fails_only_that_job_not_the_whole_run(self, mock_run):
        # A request with an unrecognized argument must produce a result file
        # (so backup_worker's own poll loop doesn't hang until its timeout)
        # rather than raising out of _process_one and aborting the run.
        request_path = self._write_request(
            "4", ["pgbackrest", "backup", "--stanza=hams_prod", "--repo1-cipher-pass=x"]
        )

        sidecar._process_one(request_path)

        mock_run.assert_not_called()
        with open(os.path.join(self._tmpdir, "result-4.json")) as f:
            result = json.load(f)
        self.assertEqual(result["return_code"], 1)
        self.assertFalse(os.path.exists(request_path))

    @patch("pgbackrest_sidecar.subprocess.run")
    def test_result_file_is_world_readable_so_the_odoo_owned_poller_can_read_it(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="")
        request_path = self._write_request("5", ["pgbackrest", "backup", "--stanza=hams_prod"])

        sidecar._process_one(request_path)

        result_path = os.path.join(self._tmpdir, "result-5.json")
        mode = os.stat(result_path).st_mode & 0o777
        self.assertEqual(mode, 0o644)

    @patch("pgbackrest_sidecar.os.chmod")
    @patch("pgbackrest_sidecar.subprocess.run")
    def test_a_failure_writing_the_result_renames_the_request_instead_of_looping(
        self, mock_run, mock_chmod
    ):
        # Advisor-caught gap, 2026-10-01: if writing/finishing the result
        # file fails for any reason, the request file must stop matching
        # PathExistsGlob=request-*.json -- otherwise hams-pgbackrest-backup.path
        # re-triggers this same request immediately, forever, until
        # systemd's StartLimitBurst trips and fails the .path unit itself.
        mock_run.return_value = MagicMock(returncode=0, stdout="ok")
        mock_chmod.side_effect = OSError("disk full")
        request_path = self._write_request("6", ["pgbackrest", "backup", "--stanza=hams_prod"])

        sidecar._process_one(request_path)  # must not raise

        self.assertFalse(os.path.exists(request_path))
        failed_path = os.path.join(self._tmpdir, "failed-6.json")
        self.assertTrue(os.path.exists(failed_path))


# [@ANCHOR: backup_management:COMM_test_pgbackrest_sidecar_main]
class TestMainProcessesEveryPendingRequest(unittest.TestCase):
    # Tests [@ANCHOR: backup_management:COMM_pgbackrest_sidecar_process_one]
    #
    # The .path unit can start this script once while several request files
    # are already queued (e.g. two on-demand triggers in quick succession) --
    # main() must drain all of them, not just one.

    def setUp(self):
        self._tmpdir = tempfile.mkdtemp(prefix="pgbackrest_sidecar_main_")
        self._patcher = patch.object(sidecar, "SPOOL_DIR", self._tmpdir)
        self._patcher.start()
        self.addCleanup(self._patcher.stop)

    @patch("pgbackrest_sidecar.subprocess.run")
    def test_drains_every_queued_request(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="ok")
        for job_id in ("10", "11", "12"):
            with open(os.path.join(self._tmpdir, f"request-{job_id}.json"), "w") as f:
                json.dump({"cmd": ["pgbackrest", "backup", "--stanza=hams_prod"], "env": {}}, f)

        sidecar.main()

        self.assertEqual(mock_run.call_count, 3)
        for job_id in ("10", "11", "12"):
            self.assertTrue(os.path.exists(os.path.join(self._tmpdir, f"result-{job_id}.json")))
            self.assertFalse(os.path.exists(os.path.join(self._tmpdir, f"request-{job_id}.json")))


if __name__ == "__main__":
    unittest.main()
