{"name": "Global Compliance & Privacy",
    "summary": "Automated configuration of GDPR/CCPA settings and legal pages.",
    "description": """
This module acts as a central hub for regulatory compliance across the project.
Upon installation, it:
- Automatically enables Odoo's native Cookie Consent Bar.
- Provisions standard editable legal pages (Privacy Policy, Cookie Policy, Terms of Service) via noupdate XML, ensuring site owner edits are never overwritten.
    """,
    "author": "Bruce Perens K6BP",
    "website": "https://perens.com/",
    "category": "Website",
    "version": "1.0",
    "license": "AGPL-3",
    "depends": ["base",
                "website",
                "portal",
                "zero_sudo",
                ],
    "data": ["security/security_data.xml",
              "security/ir.model.access.csv",
              "data/legal_pages_data.xml",
              "views/website_templates.xml",
             ],
    "knowledge_docs": [{"name": "Site Owner's Guide to Regulatory Compliance",
                        "path": "data/documentation.html",
                        "icon": "⚖️",
                        "category": "workspace",
                        }],
    "assets": {"web.assets_tests": ["compliance/static/tests/tours/compliance_tour.js",
                                    ],
               },
    "anchors": {"COMM_compliance_footer_links": "Compliance Footer Links Coverage",
                },
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
 }
