# -*- coding: utf-8 -*-
# Copyright © Bruce Perens K6BP. All Rights Reserved.
# This software is proprietary and confidential.
{   'assets': {   'web.assets_frontend': [   'ham_shack/static/src/scss/web_shack.scss',
                                             'ham_shack/static/src/js/web_shack.js',
                                             'ham_shack/static/src/js/web_transceiver.js',
                                             'ham_shack/static/src/js/s_pota_stats.js'],
                  'web.assets_qweb': [   'ham_shack/static/src/xml/web_shack.xml',
                                         'ham_shack/static/src/xml/web_transceiver.xml'],
                  'web.assets_tests': [   'ham_shack/static/tests/tours/web_shack_tour.js',
                                          'ham_shack/static/tests/tours/webrtc_tour.js']},
    'author': 'Bruce Perens K6BP',
    'auto_install': True,
    'category': 'Ham Radio',
    'data': [   'security/security_data.xml',
                'security/ir.model.access.csv',
                'security/security_rules.xml',
                'views/web_shack_templates.xml',
                'views/shack_transceiver_templates.xml',
                'views/snippets/s_pota_stats.xml'],
    'depends': [   'base',
                   'website',
                   'zero_sudo',
                   'ham_base',
                   'ham_logbook',
                   'ham_dx_cluster',
                   'user_websites',
                   'sanitizer'],
    'installable': True,
    'knowledge_docs': [   {   'category': 'workspace',
                              'icon': '📻',
                              'name': 'Ham Radio Web Shack Manual',
                              'path': 'data/documentation.html'}],
    'license': 'Other proprietary',
    'name': 'Ham Radio Shack',
    'summary': 'Unified digital interface, WebRTC integrations, and POTA stats.',
    'version': '0.4',
    'website': 'https://perens.com/'}
