# -*- coding: utf-8 -*-
import glob
import logging
import os
import pwd
import re
import shutil
import time
import urllib.request
import threading
from unittest.mock import MagicMock, patch
from odoo.tests.common import HttpCase, TransactionCase, ChromeBrowser

_logger = logging.getLogger(__name__)

# 🚨 BENIGN ERROR SCRUBBER 🚨
original_browser_stop = ChromeBrowser.stop
def _patched_browser_stop(self, *args, **kwargs):
    for attr in ['_errors', '_browser_errors', 'errors']:
        if hasattr(self, attr):
            error_list = getattr(self, attr)
            if isinstance(error_list, list):
                filtered = []
                for e in error_list:
                    msg = str(e).lower()
                    if "owl is running in 'dev' mode" in msg or "resizeobserver" in msg:
                        continue
                    filtered.append(e)
                setattr(self, attr, filtered)
    return original_browser_stop(self, *args, **kwargs)
ChromeBrowser.stop = _patched_browser_stop

# 🚨 NATIVE SCREENSHOT RESCUE 🚨
original_take_screenshot = ChromeBrowser.take_screenshot
def _patched_take_screenshot(self, *args, **kwargs):
    try:
        path = original_take_screenshot(self, *args, **kwargs)
        if hasattr(path, 'result'):
            path = path.result(timeout=20.0)

        _logger.error("TRACING: Screenshot generated by Chrome at %s", path)

        host_tmp = os.environ.get("HAMS_REAL_LOG_DIRECTORY")
        if path and os.path.exists(path) and host_tmp:
            os.makedirs(host_tmp, exist_ok=True)

            orig_user = os.environ.get("SUDO_USER", "odoo")
            orig_uid, orig_gid = -1, -1
            try:
                user_info = pwd.getpwnam(orig_user)
                orig_uid = user_info.pw_uid
                orig_gid = user_info.pw_gid
                if not os.path.exists(host_tmp):
                    os.chown(host_tmp, orig_uid, orig_gid)
            except Exception as user_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Could not resolve SUDO_USER info for chown: %s", repr(user_e))

            dst = os.path.join(host_tmp, os.path.basename(path))
            shutil.copy2(path, dst)
            try:
                if orig_uid != -1:
                    os.chown(dst, orig_uid, orig_gid)
            except Exception as chown_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Could not chown screenshot file: %s", repr(chown_e))

            _logger.error("TRACING: Successfully moved screenshot to host partition: %s", dst)
    except Exception as ss_e: # audit-ignore-catch-all
        _logger.warning("TRACING: Native screenshot failed: %s", repr(ss_e))

ChromeBrowser.take_screenshot = _patched_take_screenshot


class DiagnosticMock(MagicMock):
    def __init__(self, *args, **kwargs):
        max_depth = kwargs.pop("max_recursion_depth", 5)
        super().__init__(*args, **kwargs)
        self._max_depth = max_depth
        self._current_depth = 0

    def __call__(self, *args, **kwargs):
        self._current_depth += 1
        if self._current_depth > self._max_depth:
            self._current_depth = 0
            raise RecursionError(
                f"DiagnosticMock Security Trip: Recursion depth limit ({self._max_depth}) exceeded."
            )
        try:
            return super().__call__(*args, **kwargs)
        finally:
            self._current_depth -= 1


class SafePatchMixin:
    def safe_patch(self, target, *args, **kwargs):
        if not args and "new" not in kwargs and "new_callable" not in kwargs:
            kwargs["new_callable"] = DiagnosticMock
        patcher = patch(target, *args, **kwargs)
        mock_obj = patcher.start()
        self.addCleanup(patcher.stop)
        return mock_obj

    def safe_patch_object(self, target, attribute, *args, **kwargs):
        if not args and "new" not in kwargs and "new_callable" not in kwargs:
            kwargs["new_callable"] = DiagnosticMock
        patcher = patch.object(target, attribute, *args, **kwargs)
        mock_obj = patcher.start()
        self.addCleanup(patcher.stop)
        return mock_obj


class HamsTransactionCase(TransactionCase, SafePatchMixin):
    # [@ANCHOR: hams_transaction_case]
    pass


class HamsHttpCase(HttpCase, SafePatchMixin):
    # [@ANCHOR: hams_http_case]

    @classmethod
    def setUpClass(cls):
        # 🚨 THE ANTI-HANG INJECTION 🚨
        original_start = threading.Thread.start

        def _daemonized_start(self_thread, *args, **kwargs):
            self_thread.daemon = True
            return original_start(self_thread, *args, **kwargs)

        with patch.object(threading.Thread, 'start', new=_daemonized_start):
            super().setUpClass()

    @classmethod
    def tearDownClass(cls):
        _logger.info("TRACING: Entering HamsHttpCase.tearDownClass.")

        if hasattr(cls, 'server_thread') and cls.server_thread:
            cls.server_thread.join = lambda *args, **kwargs: None

        if hasattr(cls, 'server') and cls.server:
            try:
                if hasattr(cls.server, 'server') and hasattr(cls.server.server, 'socket'):
                    cls.server.server.socket.close()
            except Exception as close_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Ignored Exception closing server socket: %s", repr(close_e))
            cls.server.stop = lambda *args, **kwargs: None

        try:
            super().tearDownClass()
            _logger.info("TRACING: Successfully completed super().tearDownClass()")
        except Exception as e: # audit-ignore-catch-all
            if "socket is already closed" not in str(e) and "WebSocketConnectionClosedException" not in type(e).__name__:
                _logger.error("TRACING: Native teardown failed or hung: %s", e)
        finally:
            if hasattr(cls, 'browser') and cls.browser:
                if hasattr(cls.browser, 'chrome_process'):
                    try:
                        cls.browser.chrome_process.terminate()
                        cls.browser.chrome_process.wait(timeout=2.0)
                    except Exception as term_e: # audit-ignore-catch-all
                        _logger.warning("TRACING: Ignored Exception terminating chrome process: %s", repr(term_e))
                    try:
                        cls.browser.chrome_process.kill()
                    except OSError as kill_e:
                        _logger.warning("TRACING: Ignored OSError killing chrome process: %s", repr(kill_e))
                if hasattr(cls.browser, '_websocket_thread') and cls.browser._websocket_thread:
                    cls.browser._websocket_thread.join = lambda *args, **kwargs: None

            _logger.info("TRACING: Exiting HamsHttpCase.tearDownClass")

    def tearDown(self):
        _logger.info("TRACING: Entering HamsHttpCase.tearDown")

        try:
            super().tearDown()
            _logger.info("TRACING: Completed super().tearDown")
        except Exception as e: # audit-ignore-catch-all
            if "socket is already closed" not in str(e) and "WebSocketConnectionClosedException" not in type(e).__name__ and "BrokenPipeError" not in type(e).__name__:
                _logger.error("TRACING: HamsHttpCase.tearDown caught exception: %s", e)
        finally:
            if hasattr(self, 'browser') and self.browser:
                if hasattr(self.browser, 'chrome_process'):
                    try:
                        self.browser.chrome_process.terminate()
                        self.browser.chrome_process.wait(timeout=2.0)
                    except Exception as term_e: # audit-ignore-catch-all
                        _logger.warning("TRACING: Ignored Exception terminating instance chrome process: %s", repr(term_e))
                    try:
                        self.browser.chrome_process.kill()
                    except OSError as kill_e:
                        _logger.warning("TRACING: Ignored OSError killing instance chrome process: %s", repr(kill_e))
                if hasattr(self.browser, '_websocket_thread') and self.browser._websocket_thread:
                    self.browser._websocket_thread.join = lambda *args, **kwargs: None

            # Clean up the V8 profiler log directly on the host mount if the test succeeded
            if not getattr(self.__class__, '_hams_tour_failed', False):
                host_tmp = os.environ.get("HAMS_REAL_LOG_DIRECTORY", "/var/tmp")
                for log_file in glob.glob(os.path.join(host_tmp, "v8_hang*.log")):
                    try:
                        open(log_file, 'w').close()
                    except OSError as trunc_e:
                        _logger.warning("TRACING: Ignored OSError truncating V8 log: %s", repr(trunc_e))

            _logger.info("TRACING: Exiting HamsHttpCase.tearDown")

    def browser_js(self, *args, **kwargs):
        _logger.info("TRACING: Entering browser_js wrapper.")
        try:
            super().browser_js(*args, **kwargs)
            _logger.info("TRACING: super().browser_js completed successfully.")
        except Exception as e: # audit-ignore-catch-all
            self.__class__._hams_tour_failed = True

            is_watchdog = False
            current_exc = e
            while current_exc is not None:
                if "socket is already closed" in str(current_exc) or "BrokenPipeError" in type(current_exc).__name__:
                    is_watchdog = True
                    break
                current_exc = getattr(current_exc, '__context__', None)

            if not is_watchdog and hasattr(self, 'browser'):
                try:
                    self.browser.take_screenshot()
                except Exception as ss_e: # audit-ignore-catch-all
                    _logger.warning("TRACING: Ignored Exception taking fallback screenshot: %s", repr(ss_e))

            if is_watchdog:
                raise AssertionError("Tour failed due to severed Chrome websocket.") from None
            else:
                raise e from None
        finally:
            _logger.info("TRACING: Exiting browser_js wrapper.")

    def start_tour(self, *args, **kwargs):
        args_list = list(args)

        # 🚨 DYNAMIC DEBUG OVERRIDE 🚨
        # Reads HAMS_TOUR_DEBUG set by the test runner to override tour URL debug flags.
        tour_debug = os.environ.get("HAMS_TOUR_DEBUG")
        if tour_debug and args_list and isinstance(args_list[0], str):
            url_path = args_list[0]
            if "debug=" in url_path:
                url_path = re.sub(r'debug=[^&]*', f'debug={tour_debug}', url_path)
            else:
                separator = "&" if "?" in url_path else "?"
                url_path += f"{separator}debug={tour_debug}"
            args_list[0] = url_path

        args = tuple(args_list)
        _logger.info("TRACING: Entering start_tour wrapper.")

        try:
            super().start_tour(*args, **kwargs)
            _logger.info("TRACING: super().start_tour completed successfully.")
        except Exception as e:  # audit-ignore-catch-all
            self.__class__._hams_tour_failed = True
            _logger.error("\n=== TOUR FAILED OR HUNG. DUMPING COMPILED ASSETS ===")
            try:
                bundle = self.env['ir.qweb']._get_asset_bundle('web.assets_tests').js()
                dump_path = '/var/tmp/failed_tour_bundle.js'
                with open(dump_path, 'w') as f:
                    if isinstance(bundle, str):
                        f.write(bundle)
                    elif hasattr(bundle, 'decode'):
                        f.write(bundle.decode('utf-8'))
                    elif hasattr(bundle, 'raw'):
                        f.write(bundle.raw.decode('utf-8'))
                    else:
                        f.write(str(bundle))
                _logger.error("Dumped compiled JS bundle to %s", dump_path)
            except Exception as inner_e:  # audit-ignore-catch-all
                _logger.warning("TRACING: Ignored Exception dumping bundle to /var/tmp: %s", repr(inner_e))

            if isinstance(e, AssertionError):
                raise e from None
            else:
                raise e from None


class HamsIntegrationCase(HamsHttpCase):
    # [@ANCHOR: integration_daemon_testing]

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._daemons = []

    @classmethod
    def tearDownClass(cls):
        env = cls.env
        daemon_utils = env["zero_sudo.daemon.utils"]
        for process in cls._daemons:
            daemon_utils.stop_daemon_process(process)
        cls._daemons.clear()
        super().tearDownClass()

    @classmethod
    def start_daemon(cls, script_path, args=None, env_vars=None, health_url=None, timeout=600):
        env = cls.env
        daemon_utils = env["zero_sudo.daemon.utils"]
        process = daemon_utils.start_daemon_process(script_path, args, env_vars)
        cls._daemons.append(process)

        if health_url:
            start_time = time.time()
            is_healthy = False
            while time.time() - start_time < timeout:
                if process.poll() is not None:
                    raise RuntimeError(f"FATAL: Daemon process '{script_path}' crashed with exit code {process.returncode} while waiting for health check!")
                try:
                    req = urllib.request.Request(health_url)
                    with urllib.request.urlopen(req, timeout=1.0) as response:
                        if response.getcode() in (200, 204):
                            is_healthy = True
                            break
                except Exception as req_e: # audit-ignore-catch-all
                    _logger.warning("TRACING: Daemon health check not ready yet: %s", repr(req_e))
                time.sleep(0.5) # audit-ignore-sleep

            if not is_healthy:
                raise TimeoutError(f"FATAL: Daemon health check for '{script_path}' timed out after {timeout} seconds.")

        return process
