// Generated by gen_ambe_plus_2_tables.py from AMBE_PLUS_2_NOTES.md's own Annex H table
// (TIA-102.BABA-1's real bit-frame/interleave format: 36 symbols, 2 bits each, drawn from
// codewords c0..c3 for 72 total bits -- see mod.rs's own doc comment for how this fits the
// overall frame). Each entry is ((codeword, bit) for Bit1, (codeword, bit) for Bit0).

/// Annex H's own symbol table: `ANNEX_H[symbol] = ((c, bit) for Bit1, (c, bit) for Bit0)`,
/// `c` indexing codewords 0..=3 (`c0..c3`) and `bit` indexing that codeword's own bit
/// position (MSB-first widths: c0=24, c1=23, c2=11, c3=14, matching the frame layer's own
/// C0/C1/C2/C3 split).
pub const ANNEX_H: [((u8, u8), (u8, u8)); 36] = [
    ((0, 23), (0, 5)), // symbol 0
    ((1, 10), (2, 3)), // symbol 1
    ((0, 22), (0, 4)), // symbol 2
    ((1, 9), (2, 2)), // symbol 3
    ((0, 21), (0, 3)), // symbol 4
    ((1, 8), (2, 1)), // symbol 5
    ((0, 20), (0, 2)), // symbol 6
    ((1, 7), (2, 0)), // symbol 7
    ((0, 19), (0, 1)), // symbol 8
    ((1, 6), (3, 13)), // symbol 9
    ((0, 18), (0, 0)), // symbol 10
    ((1, 5), (3, 12)), // symbol 11
    ((0, 17), (1, 22)), // symbol 12
    ((1, 4), (3, 11)), // symbol 13
    ((0, 16), (1, 21)), // symbol 14
    ((1, 3), (3, 10)), // symbol 15
    ((0, 15), (1, 20)), // symbol 16
    ((1, 2), (3, 9)), // symbol 17
    ((0, 14), (1, 19)), // symbol 18
    ((1, 1), (3, 8)), // symbol 19
    ((0, 13), (1, 18)), // symbol 20
    ((1, 0), (3, 7)), // symbol 21
    ((0, 12), (1, 17)), // symbol 22
    ((2, 10), (3, 6)), // symbol 23
    ((0, 11), (1, 16)), // symbol 24
    ((2, 9), (3, 5)), // symbol 25
    ((0, 10), (1, 15)), // symbol 26
    ((2, 8), (3, 4)), // symbol 27
    ((0, 9), (1, 14)), // symbol 28
    ((2, 7), (3, 3)), // symbol 29
    ((0, 8), (1, 13)), // symbol 30
    ((2, 6), (3, 2)), // symbol 31
    ((0, 7), (1, 12)), // symbol 32
    ((2, 5), (3, 1)), // symbol 33
    ((0, 6), (1, 11)), // symbol 34
    ((2, 4), (3, 0)), // symbol 35
];

// # The TIA over-the-air interleave, and why the chip wire format may not use it
//
// `ANNEX_H` above is TIA-102.BABA-1's own specification for how the 72 logical frame bits
// (`C0||C1||C2||C3`, this module's own "logical frame" -- the format `super::parse_frame`/
// `super::build_frame` operate on) are reordered into 36 two-bit symbols for over-the-air
// transmission. `ambe_dstar`'s own real chip investigation found the DVSI chip's *wire* format
// (what it actually sends/receives over the UDP control protocol) applies exactly this kind of
// over-the-air interleave even for a direct chip/host link, apparently so a repeater needs no
// separate interleave step -- but that was confirmed empirically for D-STAR specifically, not
// assumed to generalize. Whether the chip's own AMBE+2 half-rate wire format (`RATET` 33/34) uses
// this exact Annex H interleave, some other interleave, or none at all is an open, real question
// this module's functions exist to let a live chip-capture test check directly (both hypotheses),
// not a settled fact.

/// The logical-frame bit position (0 = the 72-bit frame's own MSB) holding codeword `c`'s bit
/// `pos` (0-indexed from that codeword's own LSB, matching `ANNEX_H`'s own `c(pos)` notation),
/// given the frame layout `super::parse_frame` expects: `C0` (24 bits) at the top, then `C1` (23),
/// `C2` (11), `C3` (14).
fn codeword_frame_bit(c: u8, pos: u8) -> u32 {
    let base: u32 = match c {
        0 => 48,
        1 => 25,
        2 => 14,
        3 => 0,
        _ => panic!("codeword index must be 0..=3, got {c}"),
    };
    base + pos as u32
}

/// Applies Annex H's own interleave: reorders a 72-bit logical frame (`C0||C1||C2||C3`, packed
/// into the low 72 bits of `frame`, matching `super::parse_frame`'s input convention) into the
/// 36-symbol/72-bit over-the-air bitstream, packed MSB-first (symbol 0's `Bit1` is the returned
/// value's own bit 71).
pub fn frame_to_interleaved(frame: u128) -> u128 {
    let mut wire: u128 = 0;
    for (symbol, &((c1, p1), (c0, p0))) in ANNEX_H.iter().enumerate() {
        let bit1 = (frame >> codeword_frame_bit(c1, p1)) & 1;
        let bit0 = (frame >> codeword_frame_bit(c0, p0)) & 1;
        let pos_bit1 = 71 - 2 * symbol as u32;
        let pos_bit0 = pos_bit1 - 1;
        wire |= bit1 << pos_bit1;
        wire |= bit0 << pos_bit0;
    }
    wire
}

/// The exact inverse of [`frame_to_interleaved`]: recovers the 72-bit logical frame from Annex
/// H's own interleaved over-the-air bitstream.
pub fn interleaved_to_frame(wire: u128) -> u128 {
    let mut frame: u128 = 0;
    for (symbol, &((c1, p1), (c0, p0))) in ANNEX_H.iter().enumerate() {
        let pos_bit1 = 71 - 2 * symbol as u32;
        let pos_bit0 = pos_bit1 - 1;
        let bit1 = (wire >> pos_bit1) & 1;
        let bit0 = (wire >> pos_bit0) & 1;
        frame |= bit1 << codeword_frame_bit(c1, p1);
        frame |= bit0 << codeword_frame_bit(c0, p0);
    }
    frame
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every one of the 72 logical-frame bit positions (`C0`'s 24 down to `C3`'s 14) must be
    /// touched by `ANNEX_H` exactly once -- the same completeness invariant the generator script
    /// already checked once at generation time, re-verified here as a permanent regression guard.
    #[test]
    fn annex_h_covers_every_logical_frame_bit_exactly_once() {
        let mut seen = [false; 72];
        for &((c1, p1), (c0, p0)) in ANNEX_H.iter() {
            for (c, p) in [(c1, p1), (c0, p0)] {
                let bit = codeword_frame_bit(c, p) as usize;
                assert!(!seen[bit], "logical frame bit {bit} (c{c}({p})) claimed twice");
                seen[bit] = true;
            }
        }
        assert!(seen.iter().all(|&s| s), "not every logical frame bit is covered by Annex H");
    }

    /// The real round trip this module exists for: interleaving then deinterleaving must recover
    /// the exact original frame, checked across several structurally distinct bit patterns (all
    /// zero, all one, and two real frames built via `super::build_frame`), not just one example.
    #[test]
    fn interleave_and_deinterleave_round_trip_several_frames() {
        let all_zero: u128 = 0;
        let all_one: u128 = (1u128 << 72) - 1;
        let alternating: u128 = 0x5555_5555_5555_5555_5555u128 & ((1u128 << 72) - 1);

        for frame in [all_zero, all_one, alternating] {
            let wire = frame_to_interleaved(frame);
            let recovered = interleaved_to_frame(wire);
            assert_eq!(recovered, frame, "round trip failed for frame {frame:#x}");
        }
    }

    /// `frame_to_interleaved` must actually reorder bits (not be an accidental identity mapping)
    /// -- a real regression guard, since a bug that made every `codeword_frame_bit` call return
    /// its own wire position would still pass the round-trip test above.
    #[test]
    fn interleave_actually_reorders_bits_for_a_non_symmetric_frame() {
        let frame: u128 = 0x1234_5678_9ABC_DEF0_1234u128 & ((1u128 << 72) - 1);
        let wire = frame_to_interleaved(frame);
        assert_ne!(wire, frame, "a real interleave should reorder this non-symmetric pattern");
    }
}
