// Generated by gen_ambe_plus_2_tables.py from the real TIA-102.BABA-1 half-rate addendum
// data already extracted and verified in AMBE_PLUS_2_NOTES.md (Annexes A-D) -- see that
// file for the real source/methodology. Cross-checked value-for-value against mbelib's
// ambe3600x2450_const.h (AmbeW0table/AmbeLtable/AmbeVuv/AmbeDg) during this generation --
// exact agreement, not a coincidence (mbelib's own author transcribed the same published
// standard). Do not hand-edit; re-run the generator against the notes file instead.

/// Annex A: `b0` -> fundamental-frequency angle `omega0` (radians/sample-ish; f0 = omega0).
pub const W0_TABLE: [f64; 120] = [0.049971, 0.049215, 0.048471, 0.047739, 0.04701, 0.046299, 0.045601, 0.044905, 0.044226, 0.043558, 0.0429, 0.042246, 0.041609, 0.040979, 0.040356, 0.039747, 0.039148, 0.038559, 0.037971, 0.037399, 0.036839, 0.036278, 0.035732, 0.035198, 0.034672, 0.034145, 0.033636, 0.033133, 0.032635, 0.032148, 0.03167, 0.031122, 0.030647, 0.030184, 0.029728, 0.029272, 0.028831, 0.028395, 0.027966, 0.027538, 0.027122, 0.026712, 0.026304, 0.025906, 0.025515, 0.025129, 0.024746, 0.024372, 0.024002, 0.023636, 0.023279, 0.022926, 0.022581, 0.022236, 0.0219, 0.02157, 0.02124, 0.02092, 0.020605, 0.020294, 0.019983, 0.019684, 0.019386, 0.019094, 0.018805, 0.01852, 0.018242, 0.017965, 0.017696, 0.017431, 0.01717, 0.016911, 0.016657, 0.016409, 0.016163, 0.015923, 0.015686, 0.015411, 0.015177, 0.014946, 0.014721, 0.014496, 0.014277, 0.014061, 0.013847, 0.013636, 0.01343, 0.013227, 0.013025, 0.012829, 0.012634, 0.012444, 0.012253, 0.012068, 0.011887, 0.011703, 0.011528, 0.011353, 0.011183, 0.011011, 0.010845, 0.010681, 0.010517, 0.010359, 0.010202, 0.01005, 0.009895, 0.009747, 0.0096, 0.009453, 0.009312, 0.009172, 0.009033, 0.008896, 0.008762, 0.008633, 0.008501, 0.008375, 0.008249, 0.008125];

/// Annex A: `b0` -> harmonic count `L`.
pub const L_TABLE: [u32; 120] = [9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24, 25, 25, 26, 26, 26, 27, 27, 28, 28, 29, 29, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35, 36, 36, 37, 37, 38, 38, 39, 40, 40, 41, 42, 42, 43, 43, 44, 45, 46, 46, 47, 48, 48, 49, 50, 51, 52, 52, 53, 54, 55, 56, 56];

/// Annex B: `b1` -> 8-bit voicing pattern `v0..v7` (true = voiced).
pub const VUV: [[bool; 8]; 32] = [
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, false, false],
    [true, true, false, true, true, true, true, true],
    [true, true, true, false, true, true, true, true],
    [true, true, true, true, true, false, true, true],
    [true, true, true, true, false, false, false, false],
    [true, true, true, true, true, false, false, false],
    [true, true, true, false, false, false, false, false],
    [true, true, true, false, false, false, false, true],
    [true, true, false, false, false, false, false, false],
    [true, true, true, false, false, false, false, false],
    [true, false, false, false, false, false, false, false],
    [true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
];

/// Annex D: `b2` -> gain-delta quantizer level `delta_gamma`.
pub const DG: [f64; 32] = [-2.0, -0.67, 0.297941, 0.663728, 1.036829, 1.438136, 1.890077, 2.22797, 2.478289, 2.667544, 2.793619, 2.893261, 3.02063, 3.138586, 3.237579, 3.32257, 3.432367, 3.571863, 3.69665, 3.814917, 3.920932, 4.022503, 4.123569, 4.228291, 4.370569, 4.5437, 4.707695, 4.848879, 5.056757, 5.326468, 5.777581, 6.874496];

/// Annex C: `L` -> per-block coefficient counts `[J1, J2, J3, J4]`, indexed directly by `L`
/// (mbelib's own `AmbeLmprbl[57][4]` convention) -- entries below `L=9` are never real
/// (`L_TABLE`'s own minimum is 9) and are zero-filled padding, never read.
pub const LMPRBL: [[u32; 4]; 57] = [
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [2, 2, 2, 3],
    [2, 2, 3, 3],
    [2, 3, 3, 3],
    [2, 3, 3, 4],
    [3, 3, 3, 4],
    [3, 3, 4, 4],
    [3, 3, 4, 5],
    [3, 4, 4, 5],
    [3, 4, 5, 5],
    [4, 4, 5, 5],
    [4, 4, 5, 6],
    [4, 4, 6, 6],
    [4, 5, 6, 6],
    [4, 5, 6, 7],
    [5, 5, 6, 7],
    [5, 5, 7, 7],
    [5, 6, 7, 7],
    [5, 6, 7, 8],
    [5, 6, 8, 8],
    [6, 6, 8, 8],
    [6, 6, 8, 9],
    [6, 7, 8, 9],
    [6, 7, 9, 9],
    [6, 7, 9, 10],
    [7, 7, 9, 10],
    [7, 8, 9, 10],
    [7, 8, 10, 10],
    [7, 8, 10, 11],
    [8, 8, 10, 11],
    [8, 9, 10, 11],
    [8, 9, 11, 11],
    [8, 9, 11, 12],
    [8, 9, 11, 13],
    [8, 9, 12, 13],
    [8, 10, 12, 13],
    [9, 10, 12, 13],
    [9, 10, 12, 14],
    [9, 10, 13, 14],
    [9, 11, 13, 14],
    [10, 11, 13, 14],
    [10, 11, 13, 15],
    [10, 11, 14, 15],
    [10, 12, 14, 15],
    [10, 12, 14, 16],
    [11, 12, 14, 16],
    [11, 12, 15, 16],
    [11, 12, 15, 17],
    [11, 13, 15, 17],
];

// Annexes E/F (PRBA24/PRBA58 vector quantizers, 512+128 entries) and Annex G (the four HOC vector
// quantizers, 32+16+16+8 entries) are too large to sit inline here comfortably -- generated into
// their own files by the same script, from the same real source data (the CSVs in
// half_rate_reference/), and included directly so they live in this module's own namespace.
include!("tables_prba.rs");
include!("tables_hoc.rs");

#[cfg(test)]
mod tests {
    use super::*;

    /// Re-derives the same completeness/invariant checks the generator script already applied
    /// before writing this file, as a permanent regression guard against a future hand-edit
    /// silently breaking one of them (the generator's own checks only run once, at generation
    /// time -- these run on every `cargo test`).
    #[test]
    fn w0_table_is_strictly_decreasing() {
        for i in 0..W0_TABLE.len() - 1 {
            assert!(
                W0_TABLE[i] > W0_TABLE[i + 1],
                "W0_TABLE[{i}]={} should exceed W0_TABLE[{}]={}",
                W0_TABLE[i],
                i + 1,
                W0_TABLE[i + 1]
            );
        }
    }

    #[test]
    fn l_table_is_non_decreasing() {
        for i in 0..L_TABLE.len() - 1 {
            assert!(L_TABLE[i] <= L_TABLE[i + 1], "L_TABLE[{i}..{}] decreases", i + 1);
        }
        assert_eq!(L_TABLE[0], 9, "Annex A's own minimum L");
        assert_eq!(*L_TABLE.last().unwrap(), 56, "Annex A's own maximum L");
    }

    #[test]
    fn dg_is_strictly_increasing() {
        for i in 0..DG.len() - 1 {
            assert!(DG[i] < DG[i + 1], "DG[{i}..{}] does not increase", i + 1);
        }
    }

    #[test]
    #[allow(clippy::needless_range_loop)] // `l` is used both as the LMPRBL index and in the sum check
    fn lmprbl_blocks_sum_to_l_and_are_non_decreasing_for_every_real_l() {
        for l in 9..=56usize {
            let [j1, j2, j3, j4] = LMPRBL[l];
            assert_eq!(j1 + j2 + j3 + j4, l as u32, "L={l}: block lengths don't sum to L");
            assert!(j1 <= j2 && j2 <= j3 && j3 <= j4, "L={l}: blocks not non-decreasing");
        }
    }

    #[test]
    fn prba24_and_prba58_have_the_real_annex_e_f_entry_counts() {
        assert_eq!(PRBA24.len(), 512);
        assert_eq!(PRBA58.len(), 128);
    }

    #[test]
    fn hoc_tables_have_the_real_annex_g_entry_counts() {
        assert_eq!(HOC_B5.len(), 32);
        assert_eq!(HOC_B6.len(), 16);
        assert_eq!(HOC_B7.len(), 16);
        assert_eq!(HOC_B8.len(), 8);
    }
}
