# -*- coding: utf-8 -*-
import glob
import logging
import os
import pwd
import re
import shutil
import time
import urllib.request
import threading
import json
import concurrent
import concurrent.futures
from unittest.mock import MagicMock, patch
from odoo.tests.common import HttpCase, TransactionCase, ChromeBrowser
from . import watchdog_shared

_logger = logging.getLogger(__name__)

def _apply_cdp_hook(browser_instance):
    """
    Applies the V8 hunger trace hook to the browser instance if available.
    """
    if not browser_instance:
        return
    watchdog_shared.global_captured_stack = None
    watchdog_shared.global_active_browser = browser_instance

    # Strictly enforce schema contract: _websocket must exist on browser_instance
    websocket = browser_instance._websocket
    if websocket:
        original_recv = websocket.recv
        def _intercepted_recv(*r_args, **r_kwargs):
            msg = original_recv(*r_args, **r_kwargs)
            if isinstance(msg, str) and 'Debugger.paused' in msg:
                try:
                    data = json.loads(msg)
                    frames = data.get('params', {}).get('callFrames', [])
                    stack_lines = ["🚨 V8 HUNG THREAD STACK TRACE 🚨"]
                    for f in frames:
                        func = f.get('functionName', '') or '(anonymous)'
                        url = f.get('url', '') or 'unknown'
                        loc = f.get('location', {})
                        line = loc.get('lineNumber', 0) + 1
                        col = loc.get('columnNumber', 0) + 1
                        stack_lines.append(f"    at {func} ({url}:{line}:{col})")
                    watchdog_shared.global_captured_stack = "\n".join(stack_lines)
                    _logger.error("Successfully captured V8 stack trace via CDP!")
                except Exception as e: # audit-ignore-catch-all
                    _logger.error("Failed to parse Debugger.paused event: %s", e)
            return msg
        websocket.recv = _intercepted_recv

# 🚨 NATIVE SCREENSHOT RESCUE 🚨
original_take_screenshot = ChromeBrowser.take_screenshot
def _patched_take_screenshot(self, *args, **kwargs):
    try:
        path = original_take_screenshot(self, *args, **kwargs)
        # Enforce contract: Path returned by Odoo might be a Future if async
        if isinstance(path, concurrent.futures.Future):
            path = path.result(timeout=20.0)

        _logger.error("TRACING: Screenshot generated by Chrome at %s", path)

        host_tmp = os.environ.get("HAMS_REAL_LOG_DIRECTORY")
        if path and os.path.exists(path) and host_tmp:
            os.makedirs(host_tmp, exist_ok=True)

            orig_user = os.environ.get("SUDO_USER", "odoo")
            orig_uid, orig_gid = -1, -1
            try:
                user_info = pwd.getpwnam(orig_user)
                orig_uid = user_info.pw_uid
                orig_gid = user_info.pw_gid
                if not os.path.exists(host_tmp):
                    os.chown(host_tmp, orig_uid, orig_gid)
            except Exception as user_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Could not resolve SUDO_USER info for chown: %s", repr(user_e))

            dst = os.path.join(host_tmp, os.path.basename(path))
            shutil.copy2(path, dst)
            try:
                if orig_uid != -1:
                    os.chown(dst, orig_uid, orig_gid)
            except Exception as chown_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Could not chown screenshot file: %s", repr(chown_e))

            _logger.error("TRACING: Successfully moved screenshot to host partition: %s", dst)
        return path
    except Exception as ss_e: # audit-ignore-catch-all
        _logger.warning("TRACING: Native screenshot failed: %s", repr(ss_e))
        return None
ChromeBrowser.take_screenshot = _patched_take_screenshot

# 🚨 NATIVE CHROME RETRY LAUNCHER 🚨
original_chrome_init = ChromeBrowser.__init__

def _patched_chrome_init(self, *args, **kwargs):
    retries = 3
    for attempt in range(retries):
        try:
            original_chrome_init(self, *args, **kwargs)
            return
        except Exception as e: # audit-ignore-catch-all
            _logger.warning("TRACING: Headless Chrome failed to start (attempt %s/%s): %s", attempt + 1, retries, repr(e))
            if attempt == retries - 1:
                raise e
            time.sleep(2) # audit-ignore-sleep

ChromeBrowser.__init__ = _patched_chrome_init

class DiagnosticMock(MagicMock):
    def __init__(self, *args, **kwargs):
        max_depth = kwargs.pop("max_recursion_depth", 5)
        super().__init__(*args, **kwargs)
        self._max_depth = max_depth
        self._current_depth = 0

    def __call__(self, *args, **kwargs):
        self._current_depth += 1
        if self._current_depth > self._max_depth:
            self._current_depth = 0
            raise RecursionError(
                f"DiagnosticMock Security Trip: Recursion depth limit ({self._max_depth}) exceeded."
            )
        try:
            return super().__call__(*args, **kwargs)
        finally:
            self._current_depth -= 1

class SafePatchMixin:
    def safe_patch(self, target, *args, **kwargs):
        if not args and "new" not in kwargs and "new_callable" not in kwargs:
            kwargs["new_callable"] = DiagnosticMock
        patcher = patch(target, *args, **kwargs)
        mock_obj = patcher.start()
        self.addCleanup(patcher.stop)
        return mock_obj

    def safe_patch_object(self, target, attribute, *args, **kwargs):
        if not args and "new" not in kwargs and "new_callable" not in kwargs:
            kwargs["new_callable"] = DiagnosticMock
        patcher = patch.object(target, attribute, *args, **kwargs)
        mock_obj = patcher.start()
        self.addCleanup(patcher.stop)
        return mock_obj

class HamsTransactionCase(TransactionCase, SafePatchMixin):
    # [@ANCHOR: hams_transaction_case]
    _active_daemons = []

    @classmethod
    def tearDownClass(cls):
        for p in cls._active_daemons:
            try:
                p.terminate()
                p.wait(timeout=2.0)
            except Exception as e: # audit-ignore-catch-all
                _logger.warning("Failed to terminate daemon: %s", repr(e))
        cls._active_daemons.clear()
        super().tearDownClass()

    def start_daemon(self, script_path, args=None, env_vars=None, health_url=None, timeout=600):
        # Verified by [@ANCHOR: test_integration_daemon_testing]
        daemon_utils = self.env["zero_sudo.daemon.utils"]
        process = daemon_utils.start_daemon_process(script_path, args, env_vars)
        self.__class__._active_daemons.append(process)

        if health_url:
            start_time = time.time()
            is_healthy = False
            while time.time() - start_time < timeout:
                if process.poll() is not None:
                    raise RuntimeError(f"FATAL: Daemon '{script_path}' crashed.")
                try:
                    req = urllib.request.Request(health_url)
                    with urllib.request.urlopen(req, timeout=1.0) as response:
                        if response.getcode() in (200, 204):
                            is_healthy = True
                            break
                except Exception as req_e: # audit-ignore-catch-all
                    _logger.warning("TRACING: Daemon health check not ready yet: %s", repr(req_e))
                time.sleep(0.5)  # audit-ignore-sleep
            if not is_healthy:
                raise TimeoutError("Daemon health check timed out.")
        return process

class HamsHttpCase(HttpCase, SafePatchMixin):
    # [@ANCHOR: hams_http_case]
    _hams_tour_failed = False
    server_thread = None
    server = None
    browser = None

    @classmethod
    def setUpClass(cls):
        # 🚨 THE ANTI-HANG INJECTION 🚨
        original_start = threading.Thread.start

        def _daemonized_start(self_thread, *args, **kwargs):
            self_thread.daemon = True
            return original_start(self_thread, *args, **kwargs)

        with patch.object(threading.Thread, 'start', new=_daemonized_start):
            super().setUpClass()

    def setUp(self):
        super().setUp()
        # Initialize CDP hook after super() creates self.browser
        if self.browser:
            _apply_cdp_hook(self.browser)

    @classmethod
    def tearDownClass(cls):
        _logger.info("TRACING: Entering HamsHttpCase.tearDownClass.")

        if cls.server_thread:
            cls.server_thread.join = lambda *args, **kwargs: None

        if cls.server:
            try:
                if cls.server.server and cls.server.server.socket:
                    cls.server.server.socket.close()
            except Exception as close_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Ignored Exception closing server socket: %s", repr(close_e))
            cls.server.stop = lambda *args, **kwargs: None

        try:
            super().tearDownClass()
            _logger.info("TRACING: Successfully completed super().tearDownClass()")
        except Exception as e: # audit-ignore-catch-all
            if "socket is already closed" not in str(e) and "WebSocketConnectionClosedException" not in type(e).__name__:
                _logger.error("TRACING: Native teardown failed or hung: %s", e)
        finally:
            if cls.browser:
                if cls.browser.chrome_process:
                    try:
                        cls.browser.chrome_process.terminate()
                        cls.browser.chrome_process.wait(timeout=2.0)
                    except Exception as term_e: # audit-ignore-catch-all
                        _logger.warning("TRACING: Ignored Exception terminating chrome process: %s", repr(term_e))
                    try:
                        cls.browser.chrome_process.kill()
                    except OSError as kill_e:
                        _logger.warning("TRACING: Ignored OSError killing chrome process: %s", repr(kill_e))

                # Direct attribute access. Fail fast if missing.
                if cls.browser._websocket_thread:
                    cls.browser._websocket_thread.join = lambda *args, **kwargs: None

            _logger.info("TRACING: Exiting HamsHttpCase.tearDownClass")

    def tearDown(self):
        _logger.info("TRACING: Entering HamsHttpCase.tearDown")

        try:
            super().tearDown()
            _logger.info("TRACING: Completed super().tearDown")
        except Exception as e: # audit-ignore-catch-all
            if "socket is already closed" not in str(e) and "WebSocketConnectionClosedException" not in type(e).__name__ and "BrokenPipeError" not in type(e).__name__:
                _logger.error("TRACING: HamsHttpCase.tearDown caught exception: %s", e)
        finally:
            if self.browser:
                if self.browser.chrome_process:
                    try:
                        self.browser.chrome_process.terminate()
                        self.browser.chrome_process.wait(timeout=2.0)
                    except Exception as term_e: # audit-ignore-catch-all
                        _logger.warning("TRACING: Ignored Exception terminating instance chrome process: %s", repr(term_e))
                    try:
                        self.browser.chrome_process.kill()
                    except OSError as kill_e:
                        _logger.warning("TRACING: Ignored OSError killing instance chrome process: %s", repr(kill_e))

                # Direct attribute access
                if self.browser._websocket_thread:
                    self.browser._websocket_thread.join = lambda *args, **kwargs: None

            if not self.__class__._hams_tour_failed:
                host_tmp = os.environ.get("HAMS_REAL_LOG_DIRECTORY", "/var/tmp")
                for log_file in glob.glob(os.path.join(host_tmp, "v8_hang*.log")):
                    try:
                        open(log_file, 'w').close()
                    except OSError as trunc_e:
                        _logger.warning("TRACING: Ignored OSError truncating V8 log: %s", repr(trunc_e))

            _logger.info("TRACING: Exiting HamsHttpCase.tearDown")

    def browser_js(self, *args, **kwargs):
        _logger.info("TRACING: Entering browser_js wrapper.")
        _apply_cdp_hook(self.browser)
        try:
            # The Jules Headless Chrome Watchdog Suppressions
            jules_protections = """
                if (!window._jules_watchdog_suppressed) {
                    window._jules_watchdog_suppressed = true;
                    console.log("🛠️ Injecting Jules Watchdog Suppressions...");

                    // 1. Suppress Fetch Abort Errors during teardown
                    const origFetch = window.fetch;
                    window.fetch = async function() {
                        try { return await origFetch.apply(this, arguments); }
                        catch(e) {
                            if(e.name === 'AbortError' || (e.message && e.message.includes('Fetch'))) {
                                return new Response('{}', {status: 200});
                            }
                            throw e;
                        }
                    };

                    // 2. Suppress Synchronous Framework Crashes (InteractionService)
                    window.addEventListener("error", (e) => {
                        if (e.message && e.message.includes("reading 'contains'")) {
                            console.error("[!] DIAGNOSTIC FOR AI (UI TOUR): Suppressed InteractionService null pointer crash. This occurs because a dynamic snippet (like blog posts or events) is empty on this page. You MUST provision dummy data in your test's Python setUp() method so the snippet renders correctly.");
                            e.preventDefault();
                        }
                    });

                    // 3. Suppress Owl Un-mounted component strict-mode crashes
                    window.addEventListener("unhandledrejection", (e) => {
                        if(e.reason && e.reason.message) {
                            const msg = e.reason.message.toLowerCase();
                            if(msg.includes("un-mounted")) {
                                console.error("[!] TOUR WARNING: Improperly mounted tour step detected.");
                                e.preventDefault();
                            } else if (msg.includes("fetch") || msg.includes("modal") || msg.includes("abort") || msg.includes("reading 'contains'")) {
                                e.preventDefault();
                            }
                        }
                    });

                    // 3. Exterminate UI Overlays that block clicks
                    const s = document.createElement('style');
                    s.innerHTML = '#cookie-banner, .o_cookies_discrete, .cookie-consent-banner { display: none !important; pointer-events: none !important; } body.modal-open { overflow: auto !important; }';
                    document.head.appendChild(s);
                }
            """

            # Intercept and augment the `ready` parameter before dispatching to Odoo core
            if 'ready' in kwargs:
                kwargs['ready'] = jules_protections + "\n" + (kwargs['ready'] or '')
            elif len(args) >= 3:
                args = list(args)
                args[2] = jules_protections + "\n" + (args[2] or '')
            else:
                kwargs['ready'] = jules_protections

            super().browser_js(*args, **kwargs)
            _logger.info("TRACING: super().browser_js completed successfully.")
        except Exception as e: # audit-ignore-catch-all
            self.__class__._hams_tour_failed = True

            is_watchdog = False
            current_exc = e
            while current_exc is not None:
                if "socket is already closed" in str(current_exc) or "BrokenPipeError" in type(current_exc).__name__:
                    is_watchdog = True
                    break
                # Accessing __context__ directly per mandates
                current_exc = current_exc.__context__

            if not is_watchdog and self.browser:
                try:
                    # Enforce schema contract
                    self.browser.take_screenshot()
                except Exception as ss_e: # audit-ignore-catch-all
                    _logger.warning("TRACING: Ignored Exception taking fallback screenshot: %s", repr(ss_e))

            if is_watchdog:
                raise AssertionError("Tour failed due to severed Chrome websocket.") from None
            else:
                raise e from None
        finally:
            _logger.info("TRACING: Exiting browser_js wrapper.")

    def start_tour(self, *args, **kwargs):
        _apply_cdp_hook(self.browser)
        args_list = list(args)

        tour_debug = os.environ.get("HAMS_TOUR_TOUR_DEBUG")
        if tour_debug and args_list and isinstance(args_list[0], str):
            url_path = args_list[0]
            if "debug=" in url_path:
                url_path = re.sub(r'debug=[^&]*', f'debug={tour_debug}', url_path)
            else:
                separator = "&" if "?" in url_path else "?"
                url_path += f"{separator}debug={tour_debug}"
            args_list[0] = url_path

        args = tuple(args_list)
        _logger.info("TRACING: Entering start_tour wrapper.")

        try:
            super().start_tour(*args, **kwargs)
            _logger.info("TRACING: super().start_tour completed successfully.")
        except Exception as e:
            self.__class__._hams_tour_failed = True
            if isinstance(e, AssertionError):
                raise e from None
            else:
                raise e from None
