// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/general/trig_table.rs`: a quarter-wave sine lookup table in Q16.16,
//! computed once here (where floating point is fine -- this is a build-time generator, not part of
//! `src/ambe/fixed` itself) and checked into the tree as pure integer constants, so the fixed-point
//! crate never needs `f64` to produce them. Regenerate with:
//! `cargo run --release --example ambe_fixed_generate_trig_table > src/ambe/fixed/general/trig_table.rs`

const TABLE_LEN: usize = 257; // 256 intervals spanning [0, pi/2] inclusive of both endpoints.
const Q16_ONE: f64 = 65536.0;

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_trig_table.rs` -- do not hand-edit.");
    println!("//! Quarter-wave sine, Q16.16, {TABLE_LEN} entries spanning phase `[0, pi/2]`");
    println!("//! inclusive, i.e. entry `i` is `round(sin(i * (pi/2) / {}) * 65536)`.", TABLE_LEN - 1);
    println!();
    println!("pub const QUARTER_SINE_LEN: usize = {TABLE_LEN};");
    println!("pub const QUARTER_SINE_Q16_16: [i32; {TABLE_LEN}] = [");
    for i in 0..TABLE_LEN {
        let theta = std::f64::consts::FRAC_PI_2 * (i as f64) / ((TABLE_LEN - 1) as f64);
        let value = (theta.sin() * Q16_ONE).round() as i32;
        print!("    {value},");
        if i % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
}
