// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/ratet27/reconstruct_tables.rs`: Q16.16 versions of the float tables
//! `ambe::fixed::ratet27::reconstruct`/`prediction` need. `block_lengths_for_l`,
//! `higher_order_bit_allocation`, and `higher_order_coefficient_positions` are already pure integer
//! and reused directly from the float sibling -- not regenerated here.
//!
//! `GAIN_BIT_ALLOCATION_STEP_Q16_16[l-9][m-2]` is `gain_bit_allocation(l, m)`'s own step-size half
//! (the `bits` half needs no conversion and is read from the same real function directly wherever
//! needed).
//!
//! Regenerate with:
//! `cargo run --release --example ambe_fixed_generate_ratet27_reconstruct_tables >
//! src/ambe/fixed/ratet27/reconstruct_tables.rs`

use ham_digital_modes::ambe::float::ratet27::prediction::prediction_coefficient;
use ham_digital_modes::ambe::float::ratet27::tables::{
    gain_bit_allocation, higher_order_coefficient_sigma, higher_order_step_multiplier,
    GAIN_QUANTIZER_LEVELS,
};

const Q16_ONE: f64 = 65536.0;

fn q16(x: f64) -> i32 {
    (x * Q16_ONE).round() as i32
}

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_ratet27_reconstruct_tables.rs` -- do not hand-edit.");
    println!();

    println!("pub const GAIN_QUANTIZER_LEVELS_Q16_16: [i32; {}] = [", GAIN_QUANTIZER_LEVELS.len());
    for (i, &v) in GAIN_QUANTIZER_LEVELS.iter().enumerate() {
        print!("    {},", q16(v));
        if i % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
    println!();

    println!("/// `[l-9][m-2]` -- the step-size half of `gain_bit_allocation(l, m)`, L in 9..=56, m in 2..=6.");
    println!("pub const GAIN_BIT_ALLOCATION_STEP_Q16_16: [[i32; 5]; 48] = [");
    for l in 9u32..=56 {
        let steps: Vec<String> = (2u32..=6)
            .map(|m| q16(gain_bit_allocation(l, m).expect("valid (l, m)").1).to_string())
            .collect();
        println!("    [{}],", steps.join(", "));
    }
    println!("];");
    println!();

    println!("/// Index is `bits` (1..=10, per `higher_order_step_multiplier`'s own doc comment); index 0 unused.");
    println!("pub const HIGHER_ORDER_STEP_MULTIPLIER_Q16_16: [i32; 11] = [");
    let multipliers: Vec<String> = (0u8..=10)
        .map(|bits| q16(higher_order_step_multiplier(bits).unwrap_or(0.0)).to_string())
        .collect();
    println!("    {}", multipliers.join(", "));
    println!("];");
    println!();

    println!("/// Index is `k` (2..=10, per `higher_order_coefficient_sigma`'s own doc comment); indices 0-1 unused.");
    println!("pub const HIGHER_ORDER_COEFFICIENT_SIGMA_Q16_16: [i32; 11] = [");
    let sigmas: Vec<String> = (0u32..=10)
        .map(|k| q16(higher_order_coefficient_sigma(k).unwrap_or(0.0)).to_string())
        .collect();
    println!("    {}", sigmas.join(", "));
    println!("];");
    println!();

    println!("/// `[l-9]` -- `prediction_coefficient(l)`, L in 9..=56.");
    println!("pub const PREDICTION_COEFFICIENT_Q16_16: [i32; 48] = [");
    let coeffs: Vec<String> = (9u32..=56).map(|l| q16(prediction_coefficient(l)).to_string()).collect();
    println!("    {}", coeffs.join(", "));
    println!("];");
}
