// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/general/explog_table.rs`: two 257-entry Q16.16 tables (computed here,
//! where floating point is fine -- this is a build-time generator, not part of `src/ambe/fixed`
//! itself) so `ambe::fixed::general::explog` never needs `f64` to produce them.
//! - `LOG2_FRAC_Q16_16[i]` = `log2(1 + i/256)` for `i` in `0..=256`, spanning the fractional part of
//!   `log2` over one octave (a normalized mantissa in `[1.0, 2.0)`).
//! - `EXP2_FRAC_Q16_16[i]` = `2^(i/256)` for `i` in `0..=256`, spanning `2^f` over one unit interval.
//!
//! Regenerate with:
//! `cargo run --release --example ambe_fixed_generate_explog_tables > src/ambe/fixed/general/explog_table.rs`

const TABLE_LEN: usize = 257;
const Q16_ONE: f64 = 65536.0;

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_explog_tables.rs` -- do not hand-edit.");
    println!("//! Two Q16.16 tables, {TABLE_LEN} entries each, both spanning one octave/unit interval");
    println!("//! inclusive of both endpoints -- see the generator's own doc comment for exactly what");
    println!("//! each entry is.");
    println!();

    println!("pub const LOG2_FRAC_LEN: usize = {TABLE_LEN};");
    println!("pub const LOG2_FRAC_Q16_16: [i32; {TABLE_LEN}] = [");
    for i in 0..TABLE_LEN {
        let mantissa = 1.0 + (i as f64) / ((TABLE_LEN - 1) as f64);
        let value = (mantissa.log2() * Q16_ONE).round() as i32;
        print!("    {value},");
        if i % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
    println!();

    println!("pub const EXP2_FRAC_LEN: usize = {TABLE_LEN};");
    println!("pub const EXP2_FRAC_Q16_16: [i32; {TABLE_LEN}] = [");
    for i in 0..TABLE_LEN {
        let f = (i as f64) / ((TABLE_LEN - 1) as f64);
        let value = (f.exp2() * Q16_ONE).round() as i32;
        print!("    {value},");
        if i % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
}
