// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/ratet27/pitch_refinement_tables.rs`: the fixed-point tables for the
//! 256-point windowed DFT `S_w(m)` and the window's own 16384-point DFT `W_R(m)` (TIA-102.BABA_2003.pdf
//! section 5.1.5), computed from the floating-point sibling's real window
//! (`float::ratet27::pitch::pitch_refinement_window`) with the same formulas as
//! `float::ratet27::pitch_refinement::window_dft_16384` (that function is crate-private, so its
//! three-line sum is repeated here rather than widening its visibility).
//!
//! Regenerate with: `cargo run --release --example ambe_fixed_generate_ratet27_refinement_tables >
//! src/ambe/fixed/ratet27/pitch_refinement_tables.rs`

use ham_digital_modes::ambe::float::ratet27::pitch::pitch_refinement_window;
use std::f64::consts::PI;

const WR_HALF_RANGE: i32 = 512;

fn window_dft_16384(m: i32) -> f64 {
    let mut acc = 0.0;
    for n in -110i32..=110 {
        let theta = -2.0 * PI * (m as f64) * (n as f64) / 16384.0;
        acc += pitch_refinement_window(n) * theta.cos();
    }
    acc
}

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_ratet27_refinement_tables.rs` -- do not hand-edit.");
    println!();
    println!("/// Refinement window `w_R(n)`, `n = 0..=110` (symmetric), Q30 (the centre tap is exactly 1.0).");
    println!("pub const REFINEMENT_WINDOW_Q30: [i32; 111] = [");
    for n in 0..=110 {
        println!("    {},", (pitch_refinement_window(n) * 2f64.powi(30)).round() as i64);
    }
    println!("];");
    println!();
    println!("/// `cos(2*pi*k/256)`, `k = 0..=255`, Q30; `sin(2*pi*k/256)` is `COS_256_Q30[(k + 192) % 256]`.");
    println!("pub const COS_256_Q30: [i32; 256] = [");
    for k in 0..256 {
        println!("    {},", ((2.0 * PI * k as f64 / 256.0).cos() * 2f64.powi(30)).round() as i64);
    }
    println!("];");
    println!();
    println!("/// Half range of [`WINDOW_DFT_16384_Q22`]: it holds `W_R(m)` for `m = -{WR_HALF_RANGE}..={WR_HALF_RANGE}`.");
    println!("pub const WINDOW_DFT_HALF_RANGE: i32 = {WR_HALF_RANGE};");
    println!("/// `W_R(m)`, the 16384-point DFT of the refinement window (real, symmetric in `m`), Q22.");
    println!("pub const WINDOW_DFT_16384_Q22: [i32; {}] = [", 2 * WR_HALF_RANGE + 1);
    for m in -WR_HALF_RANGE..=WR_HALF_RANGE {
        let v = (window_dft_16384(m) * 2f64.powi(22)).round();
        assert!(v.abs() < 2f64.powi(31));
        println!("    {},", v as i64);
    }
    println!("];");
}
