// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/ambe_plus_2/tables_q16.rs`: Q16.16 versions of every AMBE+2 half-rate
//! float table `ambe::fixed::general::mbe_speech::dequantize_speech` needs, computed directly from
//! the real floating-point tables (`ambe::float::ambe_plus_2::tables`/`tables_prba`/`tables_hoc`),
//! not a re-derived formula. `L_TABLE` (already `u32`), `VUV` (already `bool`), and `LMPRBL`
//! (already `u32`) need no conversion and are reused directly from the float module instead of
//! being duplicated here.
//!
//! Regenerate with:
//! `cargo run --release --features ambe_plus_2 --example ambe_fixed_generate_ambe_plus_2_tables >
//! src/ambe/fixed/ambe_plus_2/tables_q16.rs`

// `tables.rs` pulls `tables_hoc.rs`/`tables_prba.rs` in via a textual `include!`, not a `mod`
// declaration, so every one of these lives directly under `tables::`, not a separate submodule path.
use ham_digital_modes::ambe::float::ambe_plus_2::tables::{
    DG, HOC_B5, HOC_B6, HOC_B7, HOC_B8, PRBA24, PRBA58, W0_TABLE,
};

const Q16_ONE: f64 = 65536.0;

fn q16(x: f64) -> i32 {
    (x * Q16_ONE).round() as i32
}

fn print_1d(name: &str, len: usize, values: impl Iterator<Item = f64>) {
    println!("pub const {name}: [i32; {len}] = [");
    for (i, v) in values.enumerate() {
        print!("    {},", q16(v));
        if i % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
    println!();
}

fn print_2d<const N: usize>(name: &str, len: usize, rows: impl Iterator<Item = [f64; N]>) {
    println!("pub const {name}: [[i32; {N}]; {len}] = [");
    for row in rows {
        let cells: Vec<String> = row.iter().map(|&v| q16(v).to_string()).collect();
        println!("    [{}],", cells.join(", "));
    }
    println!("];");
    println!();
}

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_ambe_plus_2_tables.rs` -- do not hand-edit.");
    println!("//! Q16.16 versions of AMBE+2 half-rate's own float tables, computed directly from them.");
    println!();

    print_1d("W0_TABLE_Q16_16", W0_TABLE.len(), W0_TABLE.iter().copied());
    // Wide pitch for synthesis: `w0 = 2*pi*f0` in Q32 radians/sample (see `voiced_synthesis`).
    println!("pub const W0_TABLE_Q32: [i64; {}] = [", W0_TABLE.len());
    for (i, f0) in W0_TABLE.iter().enumerate() {
        print!("    {},", (f0 * 2.0 * std::f64::consts::PI * 4294967296.0).round() as i64);
        if i % 4 == 3 {
            println!();
        }
    }
    println!();
    println!("];");
    println!();
    print_1d("DG_Q16_16", DG.len(), DG.iter().copied());
    print_2d::<3>("PRBA24_Q16_16", PRBA24.len(), PRBA24.iter().copied());
    print_2d::<4>("PRBA58_Q16_16", PRBA58.len(), PRBA58.iter().copied());
    print_2d::<4>("HOC_B5_Q16_16", HOC_B5.len(), HOC_B5.iter().copied());
    print_2d::<4>("HOC_B6_Q16_16", HOC_B6.len(), HOC_B6.iter().copied());
    print_2d::<4>("HOC_B7_Q16_16", HOC_B7.len(), HOC_B7.iter().copied());
    print_2d::<4>("HOC_B8_Q16_16", HOC_B8.len(), HOC_B8.iter().copied());
}
