// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/ratet27/pitch_tables.rs`: the fixed-point forms of the RATET(27) pitch
//! analysis tables (Annex B initial-pitch window, its square, the sum of its fourth powers, and the
//! Annex D lowpass filter), computed from the floating-point sibling's own tables
//! (`float::ratet27::pitch::{initial_pitch_window, lowpass_filter_tap}`) rather than retyped.
//!
//! Regenerate with: `cargo run --release --example ambe_fixed_generate_ratet27_pitch_tables >
//! src/ambe/fixed/ratet27/pitch_tables.rs`

use ham_digital_modes::ambe::float::ratet27::pitch::{initial_pitch_window, lowpass_filter_tap};

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_ratet27_pitch_tables.rs` -- do not hand-edit.");
    println!("//! Non-negative half of each symmetric table (index `|n|`).");
    println!();
    println!("/// Annex B window `w_I(n)`, `n = 0..=150`, Q31 (`round(w * 2^31)`; the window peaks near 0.092).");
    println!("pub const INITIAL_WINDOW_Q31: [i32; 151] = [");
    for n in 0..=150 {
        println!("    {},", (initial_pitch_window(n) * 2f64.powi(31)).round() as i64);
    }
    println!("];");
    println!();
    println!("/// `w_I(n)^2`, Q40 (`round(w^2 * 2^40)`), computed from the real-valued window, not from the");
    println!("/// rounded Q31 table, so the small tail values keep their precision.");
    println!("pub const INITIAL_WINDOW_SQ_Q40: [i64; 151] = [");
    for n in 0..=150 {
        println!("    {},", (initial_pitch_window(n).powi(2) * 2f64.powi(40)).round() as i64);
    }
    println!("];");
    println!();
    let w4: f64 = (-150..=150).map(|n| initial_pitch_window(n).powi(4)).sum();
    println!("/// `sum over n=-150..=150 of w_I(n)^4`, Q40.");
    println!("pub const INITIAL_WINDOW_FOURTH_SUM_Q40: i64 = {};", (w4 * 2f64.powi(40)).round() as i64);
    println!();
    println!("/// Annex D lowpass filter `h_LPF(n)`, `n = 0..=10`, Q30.");
    println!("pub const LOWPASS_Q30: [i32; 11] = [");
    for n in 0..=10 {
        println!("    {},", (lowpass_filter_tap(n) * 2f64.powi(30)).round() as i64);
    }
    println!("];");
}
