// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/tia_102_baba/parameter_encoding/b0_table.rs`: two parallel 208-entry tables
//! (`b_hat_0` is an
//! 8-bit quantizer value the spec limits to `0..=207`, TIA-102.BABA_2003.pdf section 6.1) mapping
//! every possible received `b_hat_0` directly to `omega0_tilde` (Q16.16) and `L~`, computed here by
//! calling this crate's own real, chip-cross-checked floating-point functions
//! (`tia_102_baba::parameter_encoding::dequantize_fundamental_frequency`, `tia_102_baba::vuv::harmonics_count`)
//! rather than re-deriving the formulas -- so the fixed-point table is guaranteed to agree with the
//! float sibling for every input, not just a formula that was independently retyped and might drift.
//!
//! Since `b_hat_0` only has 208 valid values, this sidesteps needing a general fixed-point division
//! or `harmonics_count` port for the decoder path entirely: every decoder call site
//! (`tia_102_baba::decode`) only ever calls these two functions with an already-dequantized `omega0_tilde`
//! that is itself always one of these 208 discrete values, so a direct lookup is exact, not an
//! approximation, and needs no interpolation.
//!
//! Regenerate with: `cargo run --release --example ambe_fixed_generate_tia_102_baba_b0_table >
//! src/ambe/fixed/tia_102_baba/parameter_encoding/b0_table.rs`

use ham_digital_modes::ambe::float::tia_102_baba::parameter_encoding::dequantize_fundamental_frequency;
use ham_digital_modes::ambe::float::tia_102_baba::vuv::harmonics_count;

const B0_COUNT: usize = 208; // 0..=207, per the spec's own stated valid range.
const Q16_ONE: f64 = 65536.0;

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_tia_102_baba_b0_table.rs` -- do not hand-edit.");
    println!("//! `OMEGA0_TILDE_Q16_16[b0]` = `round(dequantize_fundamental_frequency(b0) * 65536)`.");
    println!("//! `OMEGA0_TILDE_Q32[b0]` = `round(dequantize_fundamental_frequency(b0) * 2^32)` (the wide pitch synthesis uses).");
    println!("//! `L_HAT_FROM_B0[b0]` = `harmonics_count(dequantize_fundamental_frequency(b0))`.");
    println!("//! Both computed from the real floating-point functions, not a re-derived formula.");
    println!();

    println!("pub const B0_COUNT: usize = {B0_COUNT};");
    println!("pub const OMEGA0_TILDE_Q16_16: [i32; {B0_COUNT}] = [");
    for b0 in 0..B0_COUNT as u32 {
        let omega0_tilde = dequantize_fundamental_frequency(b0);
        let value = (omega0_tilde * Q16_ONE).round() as i32;
        print!("    {value},");
        if b0 % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
    println!();

    println!("pub const OMEGA0_TILDE_Q32: [i64; {B0_COUNT}] = [");
    for b0 in 0..B0_COUNT as u32 {
        let omega0_tilde = dequantize_fundamental_frequency(b0);
        let value = (omega0_tilde * 4294967296.0).round() as i64;
        print!("    {value},");
        if b0 % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
    println!();

    println!("pub const L_HAT_FROM_B0: [u32; {B0_COUNT}] = [");
    for b0 in 0..B0_COUNT as u32 {
        let omega0_tilde = dequantize_fundamental_frequency(b0);
        let l_hat = harmonics_count(omega0_tilde);
        print!("    {l_hat},");
        if b0 % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
}
