// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates `src/ambe/fixed/dstar/tables_q16.rs`: Q16.16 versions of every D-STAR float table
//! `ambe::fixed::general::mbe_speech::dequantize_speech` needs, computed directly from the real
//! floating-point tables/functions (`ambe::float::dstar::tables`/`decode::f0_from_b0`), not a
//! re-derived formula. `L_TABLE`/`VUV`/`LMPRBL` need no conversion and are reused directly from the
//! float module. `W0_TABLE_Q16_16` here is D-STAR's own `f0` (matching AMBE+2 half-rate's own
//! table-naming convention, despite `f0`/`w0` actually differing by a factor of `2*pi` -- see
//! `ambe::fixed::ambe_plus_2::decode`'s own doc comment for why this naming is kept anyway), computed
//! from `f0_from_b0` (a formula, not a table, in the float sibling) at every one of `L_TABLE`'s own
//! 126 possible `b0` indices -- exact for the decoder path, the same reasoning
//! `tia_102_baba::parameter_encoding::dequantize_fundamental_frequency_q16`'s own table established.
//!
//! Regenerate with:
//! `cargo run --release --example ambe_fixed_generate_dstar_tables >
//! src/ambe/fixed/dstar/tables_q16.rs`

use ham_digital_modes::ambe::float::dstar::decode::f0_from_b0;
use ham_digital_modes::ambe::float::dstar::tables::{DG, HOC_B5, HOC_B6, HOC_B7, HOC_B8, L_TABLE, PRBA24, PRBA58};

const Q16_ONE: f64 = 65536.0;

fn q16(x: f64) -> i32 {
    (x * Q16_ONE).round() as i32
}

fn print_1d(name: &str, len: usize, values: impl Iterator<Item = f64>) {
    println!("pub const {name}: [i32; {len}] = [");
    for (i, v) in values.enumerate() {
        print!("    {},", q16(v));
        if i % 8 == 7 {
            println!();
        }
    }
    println!();
    println!("];");
    println!();
}

fn print_2d<const N: usize>(name: &str, len: usize, rows: impl Iterator<Item = [f64; N]>) {
    println!("pub const {name}: [[i32; {N}]; {len}] = [");
    for row in rows {
        let cells: Vec<String> = row.iter().map(|&v| q16(v).to_string()).collect();
        println!("    [{}],", cells.join(", "));
    }
    println!("];");
    println!();
}

fn main() {
    println!("// SPDX-License-Identifier: LGPL-3.0-or-later");
    println!("//! Generated by `examples/ambe_fixed_generate_dstar_tables.rs` -- do not hand-edit.");
    println!("//! Q16.16 versions of D-STAR's own float tables, computed directly from them.");
    println!();

    let b0_count = L_TABLE.len();
    print_1d("W0_TABLE_Q16_16", b0_count, (0..b0_count as u32).map(f0_from_b0));
    print_1d("DG_Q16_16", DG.len(), DG.iter().copied());
    print_2d::<3>("PRBA24_Q16_16", PRBA24.len(), PRBA24.iter().copied());
    print_2d::<4>("PRBA58_Q16_16", PRBA58.len(), PRBA58.iter().copied());
    print_2d::<4>("HOC_B5_Q16_16", HOC_B5.len(), HOC_B5.iter().copied());
    print_2d::<4>("HOC_B6_Q16_16", HOC_B6.len(), HOC_B6.iter().copied());
    print_2d::<4>("HOC_B7_Q16_16", HOC_B7.len(), HOC_B7.iter().copied());
    print_2d::<4>("HOC_B8_Q16_16", HOC_B8.len(), HOC_B8.iter().copied());
}
