// SPDX-License-Identifier: LGPL-3.0-or-later
//! **Not production code** -- see `floating_reference/mod.rs`'s own doc
//! comment. The original, fully-`f32` non-linear pitch (NLP) estimator,
//! moved here from `codec2_3200::nlp` once that module's own `nlp_fixed`
//! (which stayed there -- production, used by `EncoderFixed`, including
//! its own fixed-point radix-2 FFT) made this the only remaining caller
//! of `nlp()`/`NlpState`. `codec2_3200::nlp` still owns, and this module
//! borrows back via `pub(crate)` imports, the pieces the fixed path's
//! own table builders read directly: `lowpass_coeffs()`/`LPF_TAPS` (read
//! by `lowpass_coeffs_q23()`), `NOTCH_A`/`CNLP` (read by
//! `notch_a_q23()`/`cnlp_q23()`), and `NDEC` (both sides' decimated
//! buffer length) -- see that module's own doc comment for why those
//! can't move here. `f0_to_wo` also stays there, shared unchanged by
//! both encoders.
//!
//! Squares the speech signal, removes its DC/near-DC component,
//! low-pass filters and decimates it, then finds the fundamental via an
//! FFT peak search with sub-multiple (octave-error) correction.
//!
//! Purely encoder-internal: a real Codec2/Codec2-mod decoder only ever
//! sees the *quantized* `Wo` index this module's estimate feeds into
//! (`quantise::encode_wo`) -- it has no way to know, and doesn't care,
//! how the encoder arrived at that estimate. That means this module has
//! full design freedom and doesn't need to reproduce the reference's own
//! decimation filter bit-for-bit (its `nlp_fir_poly` is a real designed
//! 50-tap polyphase filter, unlike `bw_gamma` or the LSP quantizer, which
//! turned out to reduce to simple formulas) -- a from-scratch
//! Hann-windowed-sinc low-pass filter, generated by formula rather than
//! a literal coefficient table, does the same anti-aliasing job before
//! decimation. The general algorithmic *shape* (square + DC-notch +
//! decimate + windowed FFT + peak search + sub-multiple correction
//! biased toward pitch continuity) is standard non-linear pitch
//! tracking, documented in the open DSP/speech-coding literature broadly
//! (not exclusive to this one codec's own source) and reimplemented here
//! from that general understanding, not translated from it.

use crate::codec2_3200::nlp::{lowpass_coeffs, CNLP, LPF_TAPS, NDEC, NOTCH_A};
use crate::codec2_3200::{M_PITCH, NLP_DEC, N_SAMP, PE_FFT_SIZE, P_MAX, P_MIN, SAMPLE_RATE};
use rustfft::num_complex::Complex32;
use rustfft::FftPlanner;

/// Persistent per-encoder pitch-estimator state.
pub struct NlpState {
    /// Squared, DC-notched signal history, one entry per original-rate
    /// sample across the `M_PITCH`-sample analysis window.
    sq: [f32; M_PITCH],
    /// DC-notch filter memory (previous input, previous output).
    mem_x: f32,
    mem_y: f32,
    /// Previous frame's estimated fundamental (Hz), used to bias
    /// sub-multiple correction toward pitch continuity.
    prev_f0: f32,
    /// Planned once and reused every call -- `wspr_sync.rs`'s own
    /// established convention in this same crate: `FftPlanner` and
    /// `plan_fft_forward` are real, non-trivial work that shouldn't
    /// repeat every 10ms frame.
    fft: std::sync::Arc<dyn rustfft::Fft<f32>>,
    /// Reused scratch buffer for the FFT -- a fixed-size stack array
    /// (`PE_FFT_SIZE` is a compile-time constant), not a `Vec`, since
    /// this runs on a real-time codec's per-10ms-sub-frame encode path.
    fft_buf: [Complex32; PE_FFT_SIZE],
}

impl Default for NlpState {
    fn default() -> Self {
        let mut planner = FftPlanner::<f32>::new();
        let fft = planner.plan_fft_forward(PE_FFT_SIZE);
        NlpState {
            sq: [0.0; M_PITCH],
            mem_x: 0.0,
            mem_y: 0.0,
            prev_f0: 100.0,
            fft,
            fft_buf: [Complex32::new(0.0, 0.0); PE_FFT_SIZE],
        }
    }
}

impl NlpState {
    pub fn new() -> Self {
        Self::default()
    }
}

/// Low-pass filters `sq` and decimates it by `NLP_DEC`, producing `NDEC`
/// output samples. Edge samples clamp to the buffer's own boundary
/// (replicate padding) rather than pulling in real history from before
/// this call's window -- a small, encoder-internal-only approximation at
/// the window's edges. `pub(crate)`: `codec2_3200::nlp`'s own
/// cross-validation tests (`decimate_fixed_matches_the_float_decimate_
/// on_realistic_amplitude_input`) call this directly.
pub(crate) fn decimate(sq: &[f32; M_PITCH]) -> [f32; NDEC] {
    let h = lowpass_coeffs();
    let half = (LPF_TAPS as isize - 1) / 2;
    let mut out = [0.0f32; NDEC];
    for (k, out_k) in out.iter_mut().enumerate() {
        let center = (k * NLP_DEC) as isize;
        let mut acc = 0.0f32;
        for (t, &coeff) in h.iter().enumerate() {
            let idx = center + t as isize - half;
            let idx = idx.clamp(0, M_PITCH as isize - 1) as usize;
            acc += coeff * sq[idx];
        }
        *out_k = acc;
    }
    out
}

/// Corrects a common non-linear-pitch failure mode: the true fundamental
/// is often weaker in the squared/decimated spectrum than one of its own
/// harmonics, so the raw global peak (`gmax_bin`) can land on `2x`,
/// `3x`, ... the real pitch frequency. Walks down through integer
/// sub-multiples of `gmax_bin`, preferring one if it's both a genuine
/// local peak and strong enough (relative to `gmax`) to plausibly be the
/// real fundamental. `pub(crate)`: `codec2_3200::nlp`'s own
/// cross-validation tests call this directly against
/// `correct_sub_multiples_fixed`.
pub(crate) fn correct_sub_multiples(
    power: &[f32],
    gmax: f32,
    gmax_bin: usize,
    prev_f0_bin: usize,
    min_bin: usize,
) -> usize {
    let mut cmax_bin = gmax_bin;
    let mut mult = 2usize;
    while gmax_bin / mult >= min_bin {
        let b = gmax_bin / mult;
        let bmin = ((0.8 * b as f32) as usize).max(min_bin);
        let bmax = ((1.2 * b as f32) as usize).min(power.len() - 1);

        let thresh = if prev_f0_bin > bmin && prev_f0_bin < bmax {
            CNLP * 0.5 * gmax
        } else {
            CNLP * gmax
        };

        let mut lmax = 0.0f32;
        let mut lmax_bin = bmin;
        for (bin, &p) in power.iter().enumerate().take(bmax + 1).skip(bmin) {
            if p > lmax {
                lmax = p;
                lmax_bin = bin;
            }
        }

        if lmax > thresh
            && lmax_bin > 0
            && lmax_bin < power.len() - 1
            && lmax > power[lmax_bin - 1]
            && lmax > power[lmax_bin + 1]
        {
            cmax_bin = lmax_bin;
        }
        mult += 1;
    }
    cmax_bin
}

/// First-order DC-blocking step: `y[n] = x[n] - x[n-1] + NOTCH_A*y[n-1]`.
/// For any constant input, `x[n] - x[n-1]` is 0 the moment the input
/// stops changing, so `y` decays geometrically toward 0 at rate
/// `NOTCH_A` from then on -- any DC or slowly-varying bias in the
/// squared signal gets rejected, regardless of its magnitude.
/// `pub(crate)`: `codec2_3200::nlp`'s own cross-validation test calls
/// this directly against `dc_notch_fixed`.
pub(crate) fn dc_notch(x: f32, mem_x: &mut f32, mem_y: &mut f32) -> f32 {
    let y = x - *mem_x + NOTCH_A * *mem_y;
    *mem_x = x;
    *mem_y = y;
    y
}

/// Estimates the fundamental frequency (Hz) of the latest frame, given
/// the encoder's current `M_PITCH`-sample speech history window (same
/// convention as `lpc::speech_to_uq_lsps`'s own `Sn`: the newest
/// `N_SAMP` samples are new since the last call, the rest is shared
/// history). Updates `state` for the next call's pitch-tracking bias.
/// `pub(crate)`: `codec2_3200::nlp`'s own cross-validation tests call
/// this directly against `nlp_fixed`.
pub(crate) fn nlp(state: &mut NlpState, sn: &[f32; M_PITCH]) -> f32 {
    let start = M_PITCH - N_SAMP;
    for (sn_i, sq_i) in sn[start..].iter().zip(state.sq[start..].iter_mut()) {
        let squared = sn_i * sn_i;
        let notch = dc_notch(squared, &mut state.mem_x, &mut state.mem_y);
        // Small constant offset avoids an all-zero input driving a
        // pathological all-zero FFT (matches the reference's own noted
        // rationale for the same +1.0 bias).
        *sq_i = notch + 1.0;
    }

    let decimated = decimate(&state.sq);

    state.sq.copy_within(N_SAMP..M_PITCH, 0);

    for c in state.fft_buf.iter_mut() {
        *c = Complex32::new(0.0, 0.0);
    }
    for (i, &d) in decimated.iter().enumerate() {
        let hann = 0.5 - 0.5 * (std::f32::consts::TAU * i as f32 / (NDEC - 1) as f32).cos();
        state.fft_buf[i] = Complex32::new(d * hann, 0.0);
    }

    state.fft.process(&mut state.fft_buf);

    const HALF: usize = PE_FFT_SIZE / 2 + 1;
    let half = HALF;
    let power: [f32; HALF] = std::array::from_fn(|i| {
        state.fft_buf[i].re * state.fft_buf[i].re + state.fft_buf[i].im * state.fft_buf[i].im
    });

    let bin_to_hz = SAMPLE_RATE as f32 / (PE_FFT_SIZE * NLP_DEC) as f32;
    let lo = (PE_FFT_SIZE * NLP_DEC / P_MAX).max(1);
    let hi = (PE_FFT_SIZE * NLP_DEC / P_MIN).min(half - 1);

    let mut gmax = 0.0f32;
    let mut gmax_bin = lo;
    for (bin, &p) in power.iter().enumerate().take(hi + 1).skip(lo) {
        if p > gmax {
            gmax = p;
            gmax_bin = bin;
        }
    }

    let prev_f0_bin = (state.prev_f0 / bin_to_hz) as usize;
    let cmax_bin = correct_sub_multiples(&power, gmax, gmax_bin, prev_f0_bin, lo);

    let f0 = cmax_bin as f32 * bin_to_hz;
    state.prev_f0 = f0;
    f0
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// Real speech is int16-scaled (this crate's own captured reference
    /// data shows `R[0]` up to ~8.6e5 and NLP's own squared-signal power
    /// reaching ~2.3e19) -- test signals use this same order of
    /// magnitude so the `+1.0` DC-bias constant in `nlp()` (there to
    /// keep an all-silence frame from driving a degenerate all-zero FFT)
    /// stays negligible here too, not dominant the way it would be at
    /// amplitude ~1.0. `pub(crate)`: `codec2_3200::nlp`'s own
    /// cross-validation tests reuse this same value.
    pub(crate) const REALISTIC_AMP: f32 = 8000.0;

    /// Feeds `f0_hz` worth of a synthetic periodic signal (fundamental
    /// plus a couple of harmonics, like real voiced speech) through
    /// enough consecutive `N_SAMP`-sample frames to reach steady state
    /// (fills the `M_PITCH` history window and lets the DC-notch settle,
    /// then estimates a few more frames), returning the last frame's
    /// estimate. `pub(crate)`: `codec2_3200::nlp`'s own cross-validation
    /// tests reuse this to synthesize the float side of an agreement
    /// check.
    pub(crate) fn estimate_synthetic_pitch(f0_hz: f32, harmonic_amps: &[f32]) -> f32 {
        estimate_synthetic_pitch_at_amp(f0_hz, harmonic_amps, REALISTIC_AMP)
    }

    pub(crate) fn estimate_synthetic_pitch_at_amp(
        f0_hz: f32,
        harmonic_amps: &[f32],
        amp_scale: f32,
    ) -> f32 {
        let mut state = NlpState::new();
        let mut phase = 0.0f32;
        let mut history = [0.0f32; M_PITCH];
        let mut last_f0 = 0.0f32;

        let n_frames = (M_PITCH / N_SAMP) + 6;
        for _ in 0..n_frames {
            history.copy_within(N_SAMP..M_PITCH, 0);
            for s in history.iter_mut().skip(M_PITCH - N_SAMP) {
                let mut v = 0.0f32;
                for (h, &amp) in harmonic_amps.iter().enumerate() {
                    v += amp * (phase * (h + 1) as f32).sin();
                }
                *s = v * amp_scale;
                phase += std::f32::consts::TAU * f0_hz / SAMPLE_RATE as f32;
            }
            last_f0 = nlp(&mut state, &history);
        }
        last_f0
    }

    #[test]
    fn finds_the_fundamental_of_a_synthetic_voiced_like_signal_across_the_valid_pitch_range() {
        for &f0 in &[70.0f32, 110.0, 150.0, 200.0, 250.0, 320.0] {
            let amps = [1.0, 0.6, 0.3, 0.15];
            let est = estimate_synthetic_pitch(f0, &amps);
            let rel_err = (est - f0).abs() / f0;
            assert!(
                rel_err < 0.05,
                "f0={f0}Hz estimated as {est}Hz, {}% error",
                rel_err * 100.0
            );
        }
    }

    /// Direct, precise test of `correct_sub_multiples` itself against a
    /// hand-built power spectrum, rather than relying on the harmonics
    /// of a synthetic signal happening (after squaring redistributes
    /// their energy across sum/difference frequencies -- not a 1:1 map
    /// from "dominant Nth harmonic" to "dominant Nx bin") to land the
    /// raw global peak exactly where a real octave error would need it.
    #[test]
    fn correct_sub_multiples_prefers_a_genuine_local_peak_at_a_sub_multiple_bin() {
        let true_bin = 40usize;
        let lo = 16usize;
        let len = 256usize;
        let mut power = vec![0.01f32; len];
        power[true_bin * 2] = 1.0; // raw global peak: an octave above the true pitch
        power[true_bin] = 0.5; // genuine local peak at the true sub-multiple, well above CNLP*gmax

        let cmax = correct_sub_multiples(&power, 1.0, true_bin * 2, 0, lo);
        assert_eq!(
            cmax, true_bin,
            "expected correction down to the true sub-multiple bin"
        );
    }

    #[test]
    fn correct_sub_multiples_leaves_the_global_peak_alone_when_no_sub_multiple_qualifies() {
        let gmax_bin = 80usize;
        let lo = 16usize;
        let len = 256usize;
        // Flat, featureless power elsewhere -- no candidate sub-multiple
        // is a genuine local peak, let alone above threshold.
        let power = vec![0.01f32; len];
        let mut power = power;
        power[gmax_bin] = 1.0;

        let cmax = correct_sub_multiples(&power, 1.0, gmax_bin, 0, lo);
        assert_eq!(
            cmax, gmax_bin,
            "nothing should have qualified for correction"
        );
    }

    #[test]
    fn dc_notch_rejects_a_large_constant_offset_regardless_of_magnitude() {
        // A first-order DC blocker's steady-state response to ANY
        // constant input is 0 (x[n]-x[n-1] becomes 0 the instant the
        // input stops changing, then y decays geometrically at rate
        // NOTCH_A) -- true regardless of how large the constant is, so
        // this is a precise, exact claim, not an approximate one.
        let mut mem_x = 0.0f32;
        let mut mem_y = 0.0f32;
        // The very first sample is a step from the filter's zeroed
        // initial memory, injecting one impulse of `big_offset` that
        // then decays geometrically at rate NOTCH_A -- needs enough
        // iterations for 0.95^n * big_offset to actually reach the
        // assertion's tolerance, not just "large n" in the abstract.
        let big_offset = 1.0e9f32;
        let mut y = 0.0f32;
        for _ in 0..2000 {
            y = dc_notch(big_offset, &mut mem_x, &mut mem_y);
        }
        assert!(
            y.abs() < 1e-3,
            "notch failed to reject a large constant offset: settled at {y}"
        );
    }

    #[test]
    fn dc_notch_passes_a_genuine_ac_component_through_largely_unattenuated_at_low_frequency() {
        // Sanity check the notch isn't *also* killing the signal it's
        // supposed to preserve -- a slowly-varying (low-frequency
        // relative to the sample rate) sinusoid should come through with
        // only modest attenuation, unlike the hard DC rejection above.
        let mut mem_x = 0.0f32;
        let mut mem_y = 0.0f32;
        let freq_hz = 150.0f32;
        let n = 2000;
        let mut max_abs = 0.0f32;
        for i in 0..n {
            let x =
                8000.0 * (std::f32::consts::TAU * freq_hz * i as f32 / SAMPLE_RATE as f32).sin();
            let y = dc_notch(x, &mut mem_x, &mut mem_y);
            if i > 200 {
                max_abs = max_abs.max(y.abs()); // skip the initial transient
            }
        }
        assert!(
            max_abs > 4000.0,
            "notch attenuated a genuine {freq_hz}Hz AC component too much: max |y|={max_abs}"
        );
    }
}
