import logging
from odoo import _, fields, models

_logger = logging.getLogger(__name__)

class PagerDutyIncidentTicketAdapter(models.Model):
    _inherit = "pager.incident"

    helpdesk_ticket_id = fields.Integer(
        string="Helpdesk Ticket ID",
        help="Stores the integer ID of the generated helpdesk ticket to remain schema-agnostic.",
        tracking=True
    )

    helpdesk_ticket_model = fields.Char(
        string="Ticket Model",
        help="The Odoo model used for the ticket (e.g. hams_helpdesk.ticket or helpdesk.ticket)."
    )

    def action_generate_helpdesk_ticket(self):
        """
        Adapter API: Dynamically resolves the helpdesk model from system parameters
        and dispatches a standard payload. Includes an emergency SMTP fallback.
        """
        # [@ANCHOR: pd_helpdesk_adapter]
        for incident in self:
            if incident.helpdesk_ticket_id:
                continue

            target_model = self.env["ir.config_parameter"].get_param(
                "pager_duty.helpdesk_model", default="hams_helpdesk.ticket"
            )

            if target_model not in self.env:
                _logger.warning("Target helpdesk model '%s' not found. Ensure the module is installed.", target_model)
                self._execute_smtp_fallback(incident, "Target model not installed.")
                continue

            assignee_id = False
            if hasattr(self.env["calendar.event"], "get_current_on_duty_admin"):
                user = self.env["calendar.event"].get_current_on_duty_admin()
                if user:
                    assignee_id = user.id

            payload = {
                "name": f"[PAGER] {incident.name}",
                "description": f"<p><strong>Severity:</strong> {incident.severity}</p><p>{incident.description or 'No description provided.'}</p>",
            }

            if assignee_id:
                payload["user_id"] = assignee_id

            try:
                try:
                    svc_uid = self.env["zero_sudo.security.utils"]._get_service_uid(
                        "pager_duty.user_pager_service_internal"
                    )
                except Exception:
                    svc_uid = self.env.user.id

                ticket = self.env[target_model].with_user(svc_uid).create(payload)
                incident.helpdesk_ticket_id = ticket.id
                incident.helpdesk_ticket_model = target_model

                if assignee_id:
                    user = self.env["res.users"].browse(assignee_id)
                    if user.partner_id:
                        self.env["calendar.event"].with_user(svc_uid).create({
                            "name": f"Incident Response: {incident.name}",
                            "start": fields.Datetime.now(),
                            "stop": fields.Datetime.add(fields.Datetime.now(), hours=1),
                            "partner_ids": [(4, user.partner_id.id)],
                            "description": f"Auto-generated by PagerDuty incident escalation for ticket #{ticket.id}.",
                        })
            except Exception as e:
                _logger.error("Helpdesk Ticket Creation Failed for Incident %s: %s", incident.name, e)
                self._execute_smtp_fallback(incident, str(e), assignee_id)

    def _execute_smtp_fallback(self, incident, error_msg, assignee_id=False):
        """
        Executes a direct SMTP page if the Helpdesk integration fails or is unreachable.
        """
        if not assignee_id:
            if hasattr(self.env["calendar.event"], "get_current_on_duty_admin"):
                user = self.env["calendar.event"].get_current_on_duty_admin()
                if user:
                    assignee_id = user.id

        if assignee_id:
            try:
                mail_svc = self.env["zero_sudo.security.utils"]._get_service_uid(
                    "zero_sudo.mail_service_internal"
                )
            except Exception:
                mail_svc = self.env.user.id

            user = self.env["res.users"].browse(assignee_id)

            body = (
                f"🚨 <b>EMERGENCY PAGE (Helpdesk Fallback)</b><br/><br/>"
                f"The Pager Duty module attempted to create a Helpdesk ticket but failed due to an internal error:<br/>"
                f"<i>{error_msg}</i><br/><br/>"
                f"<b>Incident ID:</b> {incident.name}<br/>"
                f"<b>Severity:</b> {incident.severity}<br/>"
                f"<b>Details:</b> {incident.description}"
            )

            incident.with_user(mail_svc).message_post(
                body=body,
                subject=_("🚨 PAGER DUTY FALLBACK: %s") % incident.name,
                partner_ids=[user.partner_id.id]
            )
