import logging
from odoo import _, fields, models, api

_logger = logging.getLogger(__name__)

class PagerDutyIncidentTicketAdapter(models.Model):
    _inherit = "pager.incident"

    helpdesk_ticket_id = fields.Integer(
        string="Helpdesk Ticket ID",
        help="Stores the integer ID of the generated helpdesk ticket to remain schema-agnostic.",
        tracking=True
    )

    helpdesk_ticket_model = fields.Char(
        string="Ticket Model",
        help="The Odoo model used for the ticket (e.g. hams_helpdesk.ticket or helpdesk.ticket)."
    )

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        records.action_generate_helpdesk_ticket()
        return records

    def action_generate_helpdesk_ticket(self):
        """
        Adapter API: Dynamically resolves the helpdesk model from system parameters
        and dispatches a standard payload. Includes an emergency SMTP fallback.
        """
        # [@ANCHOR: pd_helpdesk_adapter]
        for incident in self:
            if incident.helpdesk_ticket_id:
                continue

            try:
                target_model = self.env["zero_sudo.security.utils"]._get_system_param(
                    "pager_duty.helpdesk_model", default="hams_helpdesk.ticket"
                )
            except (ValueError, KeyError, AttributeError) as e:
                _logger.warning("Failed to retrieve system param for helpdesk model: %s", e)
                target_model = "hams_helpdesk.ticket"

            assignee_id = False
            if hasattr(self.env["calendar.event"], "get_current_on_duty_admin"):
                user = self.env["calendar.event"].get_current_on_duty_admin()
                if user:
                    assignee_id = user.id

            if target_model not in self.env:
                _logger.warning("Target helpdesk model '%s' not found. Ensure the module is installed.", target_model)
                self._execute_smtp_fallback(incident, "Target model not installed.", assignee_id)
                continue

            payload = {
                "name": f"[PAGER] {incident.name}",
                "description": f"<p><strong>Severity:</strong> {incident.severity}</p><p>{incident.description or 'No description provided.'}</p>",
            }

            if assignee_id:
                payload["user_id"] = assignee_id

            try:
                # Isolate specific module service accounts for scoped relational object generation
                try:
                    hd_uid = self.env["zero_sudo.security.utils"]._get_service_uid(
                        "hams_helpdesk.user_helpdesk_service"
                    )
                except (ValueError, KeyError, AttributeError) as e:
                    _logger.warning("Failed to resolve hams_helpdesk service account: %s", e)
                    hd_uid = self.env.user.id

                ticket = self.env[target_model].with_user(hd_uid).create(payload)
                incident.write({
                    'helpdesk_ticket_id': ticket.id,
                    'helpdesk_ticket_model': target_model
                })

                if assignee_id:
                    user = self.env["res.users"].browse(assignee_id)
                    if user.partner_id:
                        try:
                            pd_uid = self.env["zero_sudo.security.utils"]._get_service_uid(
                                "pager_duty.user_pager_service_internal"
                            )
                        except (ValueError, KeyError, AttributeError) as e:
                            _logger.warning("Failed to resolve pager_duty service account for calendar event: %s", e)
                            pd_uid = self.env.user.id

                        self.env["calendar.event"].with_user(pd_uid).create({
                            "name": f"Incident Response: {incident.name}",
                            "start": fields.Datetime.now(),
                            "stop": fields.Datetime.add(fields.Datetime.now(), hours=1),
                            "partner_ids": [(4, user.partner_id.id)],
                            "description": f"Auto-generated by PagerDuty incident escalation for ticket #{ticket.id}.",
                        })
            except (AccessError, UserError) as e:
                _logger.warning("Permission or Validation error during ticket creation for %s: %s", incident.name, e)
                self._execute_smtp_fallback(incident, str(e), assignee_id)
            except Exception as e: # audit-ignore-catch-all
                _logger.error("Unexpected Helpdesk Ticket Creation Failed for Incident %s: %s", incident.name, e)
                self._execute_smtp_fallback(incident, str(e), assignee_id)

    def _execute_smtp_fallback(self, incident, error_msg, assignee_id=False):
        """
        Executes a direct SMTP page if the Helpdesk integration fails or is unreachable.
        """
        if not assignee_id:
            if hasattr(self.env["calendar.event"], "get_current_on_duty_admin"):
                user = self.env["calendar.event"].get_current_on_duty_admin()
                if user:
                    assignee_id = user.id

        try:
            pd_uid = self.env["zero_sudo.security.utils"]._get_service_uid(
                "pager_duty.user_pager_service_internal"
            )
        except (ValueError, KeyError, AttributeError) as e:
            _logger.warning("Failed to resolve pager_duty service account for fallback: %s", e)
            pd_uid = self.env.user.id

        body = (
            f"🚨 <b>EMERGENCY PAGE (Helpdesk Fallback)</b><br/><br/>"
            f"The Pager Duty module attempted to create a Helpdesk ticket but failed due to an internal error:<br/>"
            f"<i>{error_msg}</i><br/><br/>"
            f"<b>Incident ID:</b> {incident.name}<br/>"
            f"<b>Severity:</b> {incident.severity}<br/>"
            f"<b>Details:</b> {incident.description}"
        )

        partner_ids = []
        if assignee_id:
            user = self.env["res.users"].browse(assignee_id)
            if user.partner_id:
                partner_ids.append(user.partner_id.id)

        incident.with_user(pd_uid).message_post(
            body=body,
            subject=_("🚨 PAGER DUTY FALLBACK: %s") % incident.name,
            partner_ids=partner_ids
        )
